### ISSUE TITLE
ground failure map buttons and tabs are faint and hard to see

### ISSUE THREAD

**Issue by kallstadt-usgs** [usgs/earthquake-eventpages#1020]
We have had several comments about the buttons that link to the maps on the ground failure summary page being too faint to see. Can they be made bolder, larger and with a blue background and bold white text?

The tabs are also rather faint and hard to notice, it's not really all that obvious that they are tabs. Perhaps they can also be made bolder with larger text and potentially boxes around each word to make them look more tab-like (like the tabs on the current version of the website).

**Comment by llastowka-usgs** [comment]
These were the default styles for material design so we are going to look into improving them across the application.  We have other tickets open for this, starting with #1071 so I will close this and the work will continue for the whole application.
