### ISSUE TITLE
Adjust proportions of ground failure scalebars

### ISSUE THREAD

**Issue by kallstadt-usgs** [usgs/earthquake-eventpages#1021]
Make the triangle bigger so it more easily catches the eye, increase the size of the text of the labels above the triangle and of the bin edges, and decrease the maximum size of the colored bar so that the text size of the words is closer in size to the text of the other labels.

**Comment by llastowka-usgs** [comment]
work with Kate and Eric to preview. This may be harder than it sounds.

**Comment by kallstadt-usgs** [comment]
The changes made look good to me. My only very minor comment is that I think it'd be good to have a smidge more whitespace between the title of each section and the numbers that are on top of the triangles.
