### ISSUE TITLE
Angular elements not installed correctly on beta

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#1047]
Check it out here:
https://earthquake.usgs.gov/beta/earthquakes/eventpage/us2000crmu/shakemap/intensity

This should be remedied by using `ng add @angular/elements` to install the package

**Comment by llastowka-usgs** [comment]
HI @dslosky-usgs  is this still an issue?

**Comment by llastowka-usgs** [comment]
Daniel addressed this
