### ISSUE TITLE
Make DYFI form submit

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#1058]
Make the form submit the information

**Comment by jdbrown-USGS** [comment]
@vinceq-usgs Do you have any guidelines for how to implement the form version number?

**Comment by vinceq-usgs** [comment]
No, we don't have any rule for the version number,  just increment whenever changes are made for debugging.

**Comment by llastowka-usgs** [comment]
@vinceq-usgs would it be okay if we tied the version number to the application version number?  It would mean there would be a lot of version changes that don't update the form, but every time the form was updated it would be tied to a release of the application.

**Comment by vinceq-usgs** [comment]
Yes I think that should be fine.
