### ISSUE TITLE
add Links back to summary pages

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#1060]

**Comment by jdbrown-USGS** [comment]
from product page link back to parent summary page.

**Comment by ehunter-usgs** [comment]
There is different terminology for the links depending upon whether there is only one contribution or if there are multiple contributions for one product. See images below:
![Screen Shot 2018-07-02 at 11.36.45 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e4d21d0fe68e0b009b69b6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246454f16b7191a379ee0c2857415b4bbc30254d58eeb9cb74fce36f34985619e8d5385b27c03f14a4b9d64de908bb748b4f82e7efd844c6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e14850a7133167e67e336e0a.png)
![Screen Shot 2018-07-02 at 11.36.13 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e4d21d0fe68e0b009b69b6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246454f16b7191a379ee0c2857415e4dbc30254d58eeb9cb74fce36f34985619e8d5385b27c03f14a4b9d64de908bb748b4f82e7efd844c6fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f348e14850a7133167e67e376e0a.png)

**Comment by ehunter-usgs** [comment]
I merged, but please read the comments I left on my review, and update: https://github.com/usgs/earthquake-eventpages/pull/1079#pullrequestreview-135503971

**Comment by ehunter-usgs** [comment]
Add focal-mechanism to the "impact" keyed array
