### ISSUE TITLE
DYFI pin

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-eventpages#1070]
- Make it look like the old one

**Comment by llastowka-usgs** [comment]
Hey @vinceq-usgs for now we are going to make the new DYFI pin look like the old DYFI pin, which is the static image. I know you want to stop sending these images eventually, at which time you could start sending the information you would like to see in the pin as a product property.  Right now there is not much to work with in the properties.

**Comment by vinceq-usgs** [comment]
That is fine. I am still creating the static images regardless, except that I am only producing geocoded products and images (no more ZIP code products/images).

If/when you decide to stop showing the DYFI pin image, how about merging DYFI product pin and DYFI Form pin into a single pin? If we take out the map, we can fit:
1. max MMI
2. Number of responses
3. Link to Form
4. Link to DYFI products

**Comment by llastowka-usgs** [comment]
Hello great. Only thing is that the form pin opens the form and the product pin opens the proct module.  We have all the pins link to one spot/do one thing so we don't put too many functions in one pin. But we have time to think about it. Maybe there is a new statistic like peak response location or something you could extract and include as a property.
