### ISSUE TITLE
Mat Tab list

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-eventpages#1071]
- Try to style the mat tab list
- Make tabs look like tabs
- Make sure they work on smaller screens
- They are too hard to see
- It should be clear which tab is selected

**Comment by ehunter-usgs** [comment]
There is a `div.mat-tab-list` that wraps all of the tab list labels `div.mat-tab-labels`. We could set the following styles on the wrapper div:
- `max-width: 100%;`  
- `overflow-x: scroll;` 

Might be worth adding some other styles to indicate that the tab list labels are scrollable. Think about `.horizontal-scrolling` styles from template.
