### ISSUE TITLE
Add Download Button to DYFI Responses

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1090]
http://localhost:4200/us2000cmy3/dyfi/responses

Allow users to download a CSV version of the table.

**Comment by ehunter-usgs** [comment]
For reference, this should work similarly to the old pages:
https://github.com/usgs/earthquake-eventpages/blob/master-pre-angular/src/htdocs/js/dyfi/DYFIResponsesView.js

A modal should open with the tab separated data selected in a` textarea`like this, https://earthquake.usgs.gov/earthquakes/eventpage/us1000eu39#dyfi

# Use the angular material dialog,
# Pass in this.responses as the data
# Create a modal dialog component that displays that formats the data and displays it in a text area as tab separated data.

**Comment by ehunter-usgs** [comment]
@cswilson-usgs let's not work on this until we finish the rest of the sprint.

**Comment by emartinez-usgs** [comment]
- Alphabetize style definitions in download-dialog.css
- download-dialog.css should be scss for consistency
- Use consistent whitespace. (eg.  `{ RomanPipe }`, not `{RomanPipe}` and `onDownload () {` not `onDownload() {` etc...)

- Not sure on why the columns were re-named and re-ordered from previous implementation. Can you comment on this @ehunter-usgs ?
