### ISSUE TITLE
Residual plots for shakemap

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#1123]
Using stationlist.json

Distance options on horizontal axis:
- rrup
- rjb
- possibly other properties

Vertical axis options
- Observed values with selectable metric (PGA, PGV, MMI ...)
- Residuals

Horizontal axis should probably be log? And the vertical axis values should be logged.

Residuals should be plotted as `ln(observations) - ln(predictions)` with the plot centered at 0.

Plot DYFI converted mmi values as circles and instrumental measurements as triangles

**Comment by dslosky-usgs** [comment]
Start with PGA/PGV toggle on y-axis and rrup on x-axis. Both should toggle log/linear
@emthompson-usgs @cbworden @wald-usgs

**Comment by dslosky-usgs** [comment]
Toggle log/linear for x and y axis
Default to log for x axis
Default to log for y unless IMT is MMI
Use distances in feature.properties.distances
Call rrup x-axis rupture distance
Use same station popup from the shakemap-stations overlay

Plot residuals by subtracting feature.properties.predictions['value'] from the measured value

**Comment by dslosky-usgs** [comment]
[] Disallow log axis for residuals
[] Change axis options to difference/ratio
[] Set min 1 for log distance axis
[] Set min 0 for linear distance axis
[] Add predicted values for regression plot -- smaller shapes different color
[] Title for RJB is "Joyner-Boore Distance (km)"

**Comment by dslosky-usgs** [comment]
- [ ] y-axis label not switching correctly
- [ ] Regression plot should be called "Predictions and Observations"
- [ ] Legend for prediction curve should be "Prediction (+/- 1 std dev)"
- [ ] Legend title should be "Explanation"
- [ ] Plot line at 0 in residual plot
- [ ] Plot line at 1 in residual ratio plot
- [ ] Mirror residual ratio plot by adding the reciprocal of the max/min to the domain

**Comment by emthompson-usgs** [comment]
Also
- [ ] Remove prediction points from plot.

**Comment by dslosky-usgs** [comment]
@emthompson-usgs and

- [ ] Keep plot domain static for rock/soil GMPE toggle
