### ISSUE TITLE
Pick zoom level for shakemap tabs

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#1128]
@emthompson-usgs and @cbworden can make it a shakemap property

**Comment by dslosky-usgs** [comment]
@emthompson-usgs @cbworden Just checking on the status of this one; any update on the shakemap property?

**Comment by cbworden** [comment]
Remind me what we want to do. Is there an existing property, or are we creating a new one. In either case what would the property be called and what values would we give it?

**Comment by emthompson-usgs** [comment]
I think the issue is that the intensity map (static screen shot of the interactive map on the shakemap landing page) has some default zoom level; then you click between the PGA/PGV/PSA contour tabs and they all seem to have a random extent, maybe based on where the contours happen to be located. It would probably be nicer if they all had the same default extent to begin with. I don't think we send a useful product property for this currently but we could just put in the shakemap grid extent that is in info.json as product properties (max/min for lat/lon).

**Comment by cbworden** [comment]
I can create a property like --property-shakemap-span=xmin/xmax where xmin and xmax are longitudes, or I and also include ymin/ymax. If that will work, it's an easy fix.

Also, on the same topic, the intensity map seems to be on a basemap of topography, but the other maps are grayscale only. Can they all be on the topo base?

**Comment by emthompson-usgs** [comment]
I'll leave the nature of the product properties to @dslosky-usgs's preferences. I agree that the basemap should be consistent. The problem with the topography is that it obscures the colored contours a bit. I'm not sure what the best default is but we may want to use whatever the web team uses as default on the main "interactive map" page.

**Comment by jmfee-usgs** [comment]
I believe we already have these properties, set by the shakemap indexer module.  That's also great if you'd like to send them explicitly:

https://usgs.github.io/pdl/userguide/products/shakemap.html

**Comment by dslosky-usgs** [comment]
Oh yeah... @jmfee-usgs is right, there are min/max lat/lon properties on the shakemap product object. I can use those, then switch to the explicit option if you end up making it.

@cbworden Leaflet uses a bounding box to set the view, so getting the both the x and y values would be ideal! I can get these already through the shakemap object as Jeremy mentioned, so it's up to you if you still want to make the explicit values

**Comment by jmfee-usgs** [comment]
I think it would be useful to send those properties, the indexer module currently reads the opening element of grid.xml to add the properties; only because we couldn't enforce that in shakemap 3.5.

**Comment by emthompson-usgs** [comment]
I think it would be best to use the properties that are already being used by pdl:
- minimum-longitude
- maximum-longitude
- minimum-latitude
- maximum-latitude

**Comment by dslosky-usgs** [comment]
I second using the properties already used by PDL; then maybe they won't have to read the grid at all?

**Comment by cbworden** [comment]
Okay, well, v4 is already setting those properties, so you should have access to them.

**Comment by emthompson-usgs** [comment]
Okay, so I guess we'll keep the same behavior for any v3 shakemaps and that will be a good reason motivate the upgrade to v4.

**Comment by cbworden** [comment]
Actually, v3 sets these properties, too.

**Comment by dslosky-usgs** [comment]
The pga/pgv/psa maps can be quite zoomed out and difficult to read... Especially with the default map layer. Are we sure this is the way we want to go? @cbworden @emthompson-usgs 

We can use tooltips (which show up when the contours are hovered over) instead of the printed pga/pgv/psa values, which should help with the readability

<img width="1064" alt="screen shot 2018-10-04 at 7 26 54 pm" src="https://user-images.githubusercontent.com/17622719/46511370-8b2d5700-c80b-11e8-9a66-e6f4707ed4a1.png">

**Comment by emthompson-usgs** [comment]
I'm not sure I understand what is going on. That map appears to be zoomed out well outside of shakemap extent. If anything, zooming to the shakemap extent should improve readability.

**Comment by dslosky-usgs** [comment]
@emthompson-usgs leaflet was "snapping" to a specific zoom level, which was making the bound setting really imprecise. It's looking good now!

**Comment by emthompson-usgs** [comment]
Got it, thanks.

**Comment by emartinez-usgs** [comment]
Use a pipe to read bounds off the shakemap product. For example...
**HTML Template**
```
<shared-map ... [bounds]="shakemap | shakemapBoundsPipe" ...></shared-map>
```
**ShakeMapBoundsPipe**
```
transform(shakemap: any): any {
  try {
    const props = shakemap.properties;
    const maximumLatitude = props['maximum-latitude'];
    const maximumLongitude = props['maximum-longitude'];
    const minimumLatitude = props['minimum-latitude'];
    const minimumLongitude = props['minimum-longitude'];

    // Do some checking to make sure properties are set, numerical, and valid

    return [
      [maximumLatitude, maximumLongitude],
      [minimumLatitude, minimumLongitude]
    ];
  } catch (e) {
    // Return some default bounds ... ?
  }
}
```
