### ISSUE TITLE
Beta Links w/ Scenarios

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#1149]
Currently the "Preview Beta" links appear on the scenario pages but try to link to non-scenario beta pages. This is not correct. Two options:

(1) Publish beta version of scenario pages and update links on current scenario pages to point to beta version of scenario pages.

(2) Suppress beta preview links when running in scenario mode.

**Comment by llastowka-usgs** [comment]
this is no longer needed
