### ISSUE TITLE
Standardize Event Page Modules

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1152]
This will be a parent ticket for all subsequent tickets in milestone 1.12.0
 - Review Code
 - Determine angular coding standards to follow
 - Ensure javascript coding standards are followed
 - Look for extraneous markup
 - Look for extraneous css styles

*Standards to follow:*

Do not abbreviate variable names
Add JavaDoc style comments to classes and methods
 - https://en.wikipedia.org/wiki/Javadoc

angular template,
 - wrap at 80 chars
 - extra element wrappers, like when ngIf statements are only wrapping one element, just add the ngIf to the element
 - make sure there are no inline-styles on elements unless it is necessary (styles should be in scss files)

typescript component,
 - wrap at 80 chars
 - two return characters after sections (imports, variable declaration, constructor, life cycle hooks)
 - remove unused constructor and life-cycle hooks (i.e. ngOnInit) blocks
 - Add code blocks to classes and methods
 - organize variables/methods
 - variables should be public
 - clean up unused @Inputs
  -- variables before constructor
  -- ng<lifecycle hooks> grouped after constructor
  -- getter/setters are organized with class methods after lifecycle hooks (based on the input name)
 - ensure all subscriptions are unsubscribed. 
 - remove constructor and lifecycle hooks if they are not used

scss
 - order attributes in alphabetical order
 - values less than one should have a leading zero (0.88em not .88em)
 - make sure files are .scss files not .css files
 - remove styles that aren’t being used
 - font sizes, 0.77em and 0.88em for smaller fonts (approx. 13px and 15px respectively)
- margins are usually 1em (gutter size)

tests
 - wrap at 80 chars
 - organize imports in alphabetical order

List of Modules:
 - core
 - dyfi
 - event-page
 - executive
 - finite-fault
 - focal-mechanism
 - ground-failure
 - impact
 - map
 - moment-tensor
 - oaf
 - origin
 - pager
 - product-page
 - region-info
 - shakemap
 - shared
 - technical
 - tell-us
 - unknown-event-page
 - waveforms

**Comment by llastowka-usgs** [comment]
NIce job, thanks for getting all this down
