### ISSUE TITLE
Download component is fetching contents.xml over and over

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1153]
We currently have custom logic inside the download.component that keeps track of the toggled state and fetches the product contents when the expansion panel is opened.

Read documentation on expansion panel:
https://material.angular.io/components/expansion/api

It looks like you could just listen for the `opened` event and load the contents when that event is fired. We don't need the `closed` event to fire anything. 

Also, cache the contents.xml response. We only need to fetch the contents the first time, don't fetch every time it's toggled open. Currently, it is making an HTTP request each time the panel is toggled open. 

Also you could add an `opened` input to the download.component if you wanted the panel to be toggled open by default.

**Comment by ehunter-usgs** [comment]
consider service workers

**Comment by jmfee-usgs** [comment]
When browser caching is enabled contents.xml is loaded from cache, so this may not be critical.

**Comment by llastowka-usgs** [comment]
This is all valid, but nothing we would really ever address
