### ISSUE TITLE
Update coding standards for dyfi

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1155]
Follow steps from:
https://github.com/usgs/earthquake-eventpages/issues/1152

**Comment by ehunter-usgs** [comment]
@dslosky-usgs your PR looked good so I merged it, I just included a PR of my own to show you some of the things that you missed in your update to the coding standards. We really need a document for this stuff. 

https://github.com/usgs/earthquake-eventpages/pull/1217

**Comment by dslosky-usgs** [comment]
Looks like I caught about... half. Thanks for cleaning it up @ehunter-usgs
