### ISSUE TITLE
Event with 404 response should load unknown event page

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1185]
To recreate:
https://earthquake.usgs.gov/beta/earthquakes/eventpage/eddieevent/executive

When a query to the event ws is done with the eventid a 404 is returned. This should show the unknown event page at this point.

**Comment by emartinez-usgs** [comment]
Closing the DYFI form should take you back to the previous route when  navigating within the application. If going "back" leaves the application, maybe stay on tellus page or navigate to executive summary page.

This may be getting overly complicated with the DYFI form.

**Comment by jdbrown-USGS** [comment]
Once the tell us page is loaded by navigating to an unknown event clicking the back button creates an endless loop reloading the tell us page.

**Comment by jdbrown-USGS** [comment]
https://angular.io/api/router/NavigationExtras#skipLocationChange
