### ISSUE TITLE
DYFI Intensity Vs. Distance updates

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#1197]
Intensity vs. Distance:
- Add number of responses to the popup
- Scale transparency with nresp
- Plot the IPE lines above the user entry points

~~Cap x-axis for Responses vs. time to 24 hours~~
~~Add symbology to legend~~ moved to #1350 
~~Add text search to responses table~~ moved to #1349

**Comment by vinceq-usgs** [comment]
Other requests: 
1. on the intensity vs distance plot, plot the IPE lines above the user entry points
2. on the time vs responses plot, limit x axis to 24 hours after event

**Comment by dslosky-usgs** [comment]
Is the number of responses currently being shipped in the data somewhere? I'm not seeing it in the [plot_atten](https://earthquake.usgs.gov/realtime/product/dyfi/us2000hiw5/us/1537881773456/dyfi_plot_atten.json) for [this](https://earthquake.usgs.gov/earthquakes/eventpage/us2000hiw5#dyfi) recent event.

The responses vs. time plot should be limited to 24 hours already; did you see an event where this wasn't the case?

**Comment by vinceq-usgs** [comment]
1. It's in the event_data.xml. Should I put it in the plot_atten json also?
2. https://dev-earthquake.cr.usgs.gov/beta/earthquakes/eventpage/se609212/dyfi/responses-vs-time

**Comment by vinceq-usgs** [comment]
Daniel, I can put that data in the dyfi_plot_atten.json file.
- number of responses (total)
- number of responses for each point

Transparency is a simple function, opacity=1 for nresponses>5 else opacity=0.2.

Anything else?

**Comment by dslosky-usgs** [comment]
I think that'll do it, let me know when there's some data to play with!

**Comment by dslosky-usgs** [comment]
I'm gonna break this issue up into some smaller chunks

**Comment by vinceq-usgs** [comment]
Daniel, I updated the json file. Grab it from here:
https://dev-earthquake.cr.usgs.gov/beta/earthquakes/eventpage/se609212/dyfi/

**Comment by dslosky-usgs** [comment]
@vinceq-usgs it looks like you added some min/max x fields, but I don't see the number of responses for the individual points... is it hiding somewhere?

**Comment by vinceq-usgs** [comment]
Looks like it isn't updating... I'll see what's going on. In the meantime, here's the json file.
The additional data is under the "scatterplot1" dataset.

[dyfi_plot_atten.json.txt](https://github.com/usgs/earthquake-eventpages/files/2425318/dyfi_plot_atten.json.txt)

**Comment by dslosky-usgs** [comment]
Ah, perfect, thanks @vinceq-usgs!
