### ISSUE TITLE
Beta Event Pages - streamline DYFI Form geolocation?

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/earthquake-eventpages#1205]
Can we simplify how the user gets their location on the DYFI form? Right now I need 4 clicks:
- Click on icon to center map
- Click on icon again to popup the "Choose a location"
- Click on "Find a location" to expand the field
- Click on "Find current location"
At this point, the map switches to the geocoded location, but there's no indication of what to do next, especially if the map is taking up all of the screen. What about putting a note like "scroll down for the questionnaire" below the map but still visible on the screen?

**Comment by llastowka-usgs** [comment]
we changed the form in 1.21 so this can be considered done in that version.
