### ISSUE TITLE
Add global style for horizontal scrolling

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1212]
The `.horizontal-scrolling` style is applied on the oaf/forecast.component this should be applied to more tables on the eventpages:
 - origin/phases.component
 - origin/magnitude-detail.component
 - oaf/forecast.component
 - technical summary tables
 - impact summary tables

Make sure there aren't any other places this should be done.

**Comment by cswilson-usgs** [comment]
Will also have to consider the fact that origin/details is no longer a mat-table (after those changes get merged) so I will re-visit this to see if the current .horizontal-scrolling class works the same as on a dl element as a mat-table element

**Comment by cswilson-usgs** [comment]
rebased with master this morning 9/18/18, then re-pushed to origin issue-1212
