### ISSUE TITLE
Update Change Detection Strategy

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1234]
See Brian Love's notes:
 - Use ChangeDetectionStrategy.onPush, this will tell us when changes occur instead of constantly checking to see if anything has changed
 - tell angular that we are using immutable objects? 
 - Use `trackBy` option for *ngFor directive

**Comment by jdbrown-USGS** [comment]
created new ticket for immutable objects.

**Comment by emartinez-usgs** [comment]
- Trailing comma in imports in beachball.component.ts


Maybe just explain the following. Maybe fix if appropriate.

Some components should have OnPush added ...
- src/app/moment-tensor/axes/axes.component.ts
- src/app/origin/magnitude-detail/magnitude-detail.component.ts

Not sure why OnPush was added ...
- src/app/shared/download-dialog/download-dialog.component.ts
- src/app/shared/ngx-charts/line-chart/line-chart/line-chart.component.ts

Loops with missing trackBy ...
- src/app/dyfi/responses/dialog-responses.html
- src/app/event-page/event-page/event-page.component.html
- src/app/executive/executive/executive.component.html
- src/app/impact/impact/impact.component.html
- src/app/shakemap/station-list/station-list.component.html
- src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.html
- src/app/shared/ngx-charts/line-chart/line-chart/line-chart.component.html
- src/app/shared/product-attribution/product-attribution.component.html
- src/app/technical/technical/technical.component.html
- src/app/tell-us/question/question.component.html
