### ISSUE TITLE
Highlight active page in side navigation

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1240]
On the beta pages we do not currently have any indication of the currently selected page.

**Comment by ehunter-usgs** [comment]
I need this merged, so that I can finish with the ticket:
https://github.com/usgs/hazdev-template/pull/302

**Comment by emartinez-usgs** [comment]
Merged.

See also: https://github.com/usgs/hazdev-template/pull/303

Merging sooner than later can prevent an unnecessary hazdev-template release increment.
