### ISSUE TITLE
Rethink map on DYFI Tell Us form

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1246]
People are confused because once they enter their location on the map they think that the submit button is to accept their location on the map, this is false they need to continue filling out the form. 

We need to make it clear that once the pin is on the map that is your location. Consider just displaying the location inputs and then hiding the map in an expansion panel that would be collapsed. If we just listed the users location as text on the page (with the location on a map inside a collapsed expansion panel) then the user would see the rest of the form below, but could still verify their location on a map.

**Comment by vinceq-usgs** [comment]
Couple of issues with the current form.
1.  It takes three clicks to get user's location: click on the "target" icon, click on "Find Current Location" tab, then click on "Find Current Location" button.

2. When the location is found, there is no indication what to do next. (See screenshot below.) The correct next action is to scroll down to the rest of the form; but there is no instruction to do that, plus on my laptop, scrolling down outside the  popup, or on the bottom of the popup, doesn't work.

(Scrolling on the map works too; but I'm conditioned that scrolling the map moves the map viewpoint and not the window)

I suggest putting "Scroll down for the rest of the form" on the bottom of the popup, once a location is selected.

<img width="1170" alt="screen shot 2018-10-14 at 1 46 16 pm" src="https://user-images.githubusercontent.com/16106146/47120429-81e8b500-d223-11e8-92fc-12846038c316.png">

**Comment by llastowka-usgs** [comment]
we redid this in 1.21
