### ISSUE TITLE
Beta pages Dyfi responses vs time scale 

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#1262]
Says hours when legacy says minutes

**Comment by vinceq-usgs** [comment]
Log-time x axis should be linear time instead

**Comment by dslosky-usgs** [comment]
@vinceq-usgs @wald-usgs  it sounded like there was some interest in using a log scale for this... but maybe it's not what we want? No problem changing it back!

**Comment by vinceq-usgs** [comment]
In the current pages, the dyfi_plot_numresp.json file has the time in seconds, and also a preferred unit (e.g. "hours") and a preferred conversion from that unit to seconds (e.g. 3600). 

For simplicity we can do away with this and just have a simple logic tree on the event page side:
x axis maximum = 1 hour if max t < 1 hour, else 1 day

**Comment by vinceq-usgs** [comment]
Hi Daniel, resp vs time plot should be linear-linear scale.
