### ISSUE TITLE
Show small values as < X

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#1293]
For landslide area, `< 0.1 km^2`
For landslide population, `< 10`
For liquefaction area, `< 1 km^2`
For liquefaction population, `< 100`

**Comment by jmfee-usgs** [comment]
technically this occurs here:

https://github.com/usgs/earthquake-eventpages/blob/master/src/app/ground-failure/alert-bar/alert-bar.component.html#L52


Check for `(first && value <= bin.min)` and add less than symbol instead of 0

**Comment by llastowka-usgs** [comment]
we need to talk to @emthompson-usgs before you do this about details.  Eric the sooner you get down the sooner they can start

**Comment by emartinez-usgs** [comment]
@kallstadt-usgs @emthompson-usgs 
The lowest bin for liquefaction population exposure is currently listed as "10 - 1,000". Is this correct? It makes the first bin an order of magnitude larger than any other bin. Should we keep "10 - 1,000" or should it be "100 - 1,000" ?

Note: The lower bound is not rendered on the event page, so it is unclear that this first bin is secretly much larger than all the other bins.

**Comment by emthompson-usgs** [comment]
My understanding is that all bins should be one order of magnitude between edges for consistency and so "100 - 1,000" would be correct.

**Comment by ehunter-usgs** [comment]
@jdbrown-usgs I merged your PR, can you update and submit a new PR that reflects Eric's comments?

**Comment by ehunter-usgs** [comment]
example event:
ci38038071
