### ISSUE TITLE
Impact Versioning

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#1296]
Add version summary to top of ShakeMap, PAGER, and Ground Failure product pages.

Above tabs (if tabs). First thing on product page.

Small text similar styles to "contributed by" text. `Version X`

**Comment by jmfee-usgs** [comment]
Recommend implementing as part of product page header component, enabled in the selected impact pages via an optional parameter `showVersion` that is `false` by default:

https://github.com/usgs/earthquake-eventpages/blob/master/src/app/product-page/header/header.component.html

**Comment by ehunter-usgs** [comment]
example event:
us2000hd8v
