### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#1312]
Should probably have these. Basic at least. Custom events could also be good.

**Comment by ehunter-usgs** [comment]
I'm not sure what needs to be done for this, do we just need to add a key to the template? Or do we only want it for this one app?

**Comment by jmfee-usgs** [comment]
@ehunter-usgs : use the same script as the website, this will include the analytics script and correct UA key
https://github.com/usgs/earthquake-website/blob/master/src/htdocs/_config.inc.php#L42

Then, tap into the router as described here and send events to the existing analytics:
https://codeburst.io/using-google-analytics-with-angular-25c93bffaa18
