### ISSUE TITLE
Contours

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/earthquake-eventpages#1315]
@dslosky-usgs These are issues for ShakeMap 4 version of the product. The properties may not be included in version 3 so it is necessary for the page to behave reasonably when they are missing:
- Set contour color based on the geojson property "color" in the contour.json files
- Set contour width based on the "weight" property. 

Also, the PSA contour file names have changed and in ShakeMap version 4 these files are not being found. For example:
cont_psa03.json &rarr; cont_psa3p0.json

**Comment by dslosky-usgs** [comment]
We're looking for the new file names when the PSA tab is generated [here]( https://github.com/usgs/earthquake-eventpages/blob/92f57ef65f1bc20151a58cae1ca95317481bb82d/src/app/shakemap/shakemap/shakemap.component.html#L41), and in the actual map layer [here](https://github.com/usgs/earthquake-eventpages/blob/92f57ef65f1bc20151a58cae1ca95317481bb82d/src/app/shared/map-overlay/shakemap-psa03-overlay.ts#L38), but they're being [ignored within the PSA tab](https://github.com/usgs/earthquake-eventpages/blob/92f57ef65f1bc20151a58cae1ca95317481bb82d/src/app/shakemap/psa/psa.component.html#L6). Use [this even](https://dev01-earthquake.cr.usgs.gov/beta/earthquakes/eventpage/us2000hhfi/shakemap/psa?source=us&code=us2000hhfi_sm4) for testing
