### ISSUE TITLE
ShakeMap Pin icon

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/earthquake-eventpages#1318]
@dslosky-usgs Bruce just added 'pin-thumbnail.png' to the product downloads. We think that this might be a good alternative to the current card design. We suggest moving the icon for "Estimated intensity" to the upper right corner to be consistent with how the PAGER summary alert is displayed on its card and then use this thumbnail to fill out the rest of the card like the maps for regional information or the interactive map.

**Comment by dslosky-usgs** [comment]
@emthompson-usgs @cbworden Any good ideas for a caption for the thumbnail image? Something like "Predicted Intensity Map" ... DYFI's is currently "Community Internet Intensity Map"

**Comment by dslosky-usgs** [comment]
Thoughts?

<img width="245" alt="screen shot 2018-09-26 at 11 04 37 am" src="https://user-images.githubusercontent.com/17622719/46096286-0a6fba80-c17c-11e8-8e19-931c9cfff790.png">

**Comment by cbworden** [comment]
The thumbnail is an stylized representation of the actual intensity map. It is intentionally pixelated with randomized sampling, and the x/y proportions are distorted to make it square. It's more of a logo than a map. I suggest not giving it a title.

**Comment by dslosky-usgs** [comment]
I like the abstract representation; maybe @vinceq-usgs is interested in what you've done. I can forgo the thumbnail title for now and we can talk about adding one later if people want

**Comment by cbworden** [comment]
FWIW, starting with the next ShakeMap update, the thumbnail will use the MMI colormap and scaling, so it will match the actual intensity map a little better.

**Comment by dslosky-usgs** [comment]
Sounds good @cbworden. Another option is to add some data to the caption... not sure if @jmfee-usgs  might have some feelings about this

<img width="249" alt="screen shot 2018-09-26 at 11 50 00 am" src="https://user-images.githubusercontent.com/17622719/46098877-94bb1d00-c182-11e8-88a4-141672e1f305.png">

**Comment by dslosky-usgs** [comment]
Also, just FYI, I'm just using one pin-thumbnail for testing on my local machine; just in case the red in the thumbnail for that 3 MMI event is making you self conscious @cbworden

**Comment by ehunter-usgs** [comment]
@dslosky-usgs, I am just wondering if we are a bit premature with this change? Generally when someone clicks on a pin and it opens that product's module you see something that similar to what was on the pin, but in more detail. Will we have a similar overlay/image on the shakemap page?

**Comment by dslosky-usgs** [comment]
@ehunter-usgs I'm definitely interested to hear your thoughts. You won't get a similar image when you click through to the shakemap page... but the shakemap page doesn't look like the "data-view" pin either :)
