### ISSUE TITLE
figure out image in banner

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#1328]
Displaying image breaks all the tests, figure out how to do both

**Comment by jmfee-usgs** [comment]
see https://github.com/usgs/hazdev-template/pull/301

**Comment by emartinez-usgs** [comment]
See comments in hazdev-template PR.

**Comment by emartinez-usgs** [comment]
A hack: https://github.com/usgs/hazdev-template/pull/303

**Comment by emartinez-usgs** [comment]
Fixed by #1335
