### ISSUE TITLE
DYFI "Thumbnails" are huge

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1355]
I was looking at some newer events and saw that the image sizes for the thumbnails that we are loading are around 800KB.

https://dev-earthquake.cr.usgs.gov/beta/earthquakes/eventpage/us2000hd8v/executive

Are these the images that we will be using? Can we come up with a check for pins that evaluates the `length` property before loading the thumbnail and then falls back to a data only pin?  This would encourage stakeholders to send smaller images.

**Comment by llastowka-usgs** [comment]
Did we contact @vinceq-usgs about sending smaller images? If not here it is...

**Comment by dslosky-usgs** [comment]
@vinceq-usgs and I have been chatting about this! He's working on generating a thumbnail

**Comment by vinceq-usgs** [comment]
I was discussing this with Daniel earlier... For the largest events, even, an abbreviated JSON file (low precision, no data) is still in the order of tens of Kb. I tried creating a PNG and I can't manage to get it much less than 20Kb, but a JPG seems to have much better compression.
![dyfi_map_geo_10km_thumbnail](https://user-images.githubusercontent.com/16106146/46223268-c0b3db00-c307-11e8-8031-f7730074f4ae.jpg)

**Comment by vinceq-usgs** [comment]
Linda, this feature is live on the (beta) DYFI4 version. Should I go and change the production DYFI? Will the production Event Pages be able to handle the new filename?

**Comment by dslosky-usgs** [comment]
@vinceq-usgs point me to an example product and I will build it in with the existing pin image as a fallback!

**Comment by vinceq-usgs** [comment]
@dslosky-usgs here's the latest event that has one.
https://dev01-earthquake.cr.usgs.gov/realtime/product/dyfi/nc73093981/us/1538761939000/dyfi_map_geo_10km_thumbnail.jpg

**Comment by vinceq-usgs** [comment]
Daniel I'd like to discuss the filenames that the Event Pages use. As far as I can tell there are "magic names" that the webpage is looking for to display, e.g. 
[eventid]_ciim_geo.jpg - the image map
contents.xml - list of products + description(?) redundant?
event_data.xml - product information + list of products + description(?) 
Is there anything else? We should either document this, or make it customizable somehow.
