### ISSUE TITLE
Compass Winds Calculation

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#1369]
For example: us1000h3p4

First and final two cities show direction as "undefined". May be related to mod 360 calculation or some other edge case.

**Comment by ehunter-usgs** [comment]
https://github.com/usgs/earthquake-geoserve-ui/pull/110

Then I will need to release a new version of hazdev-ng-geoserve and increment the dependencies in earthquake-eventpages

**Comment by emartinez-usgs** [comment]
- Need to re-publish geoserve component in npm.
- Update version of hazdev-ng-geoserve-output used by this application.
