### ISSUE TITLE
Banner and Social Icons

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#1370]
CSS images still not showing. Possibly already fixed in template, but dependency may need to be updated to latest to see corrections.

**Comment by ehunter-usgs** [comment]
use data uri
https://github.com/usgs/hazdev-template/pull/305

**Comment by ehunter-usgs** [comment]
This is just waiting for a new release of hazdev-ng-template, waiting until all other issues are merged.
