### ISSUE TITLE
Legend on shakemap product page

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/earthquake-eventpages#1372]
This issue came up previously and my recollection is that we decided to use a single static legend below the map on the product landing page as a short term solution. I'd like to try to figure out what a better long term solution is. @mhearne-usgs is currently improving the legends on the static maps and I think it makes sense to revisit this at the same time. 

Here are the options I can think of: 
1) We can update the current legend so that it does not vary with event. This means stripping off the PGA and PGV rows of the legend. I don't think this option is popular because these rows provide a link between instrumentally recorded shaking and perceived shaking and damage which is very useful for a general audience. 
2) Provide a new file in the download list for each product that can be used here. 
3) Provide a product property that says which legend file to use and the legend files will be stored/accessed the same as the current legend file. The benefit of this over the one above is that there are only a few different types of legends so it seems kind of wasteful to store a separate file for each event. 

Tagging some people that may want to comment or provide other ideas: 
@wald-usgs 
@cbworden 
@jmfee-usgs 
@emartinez-usgs 
@dslosky-usgs

**Comment by dslosky-usgs** [comment]
@emthompson-usgs it sounds like option 3 might be a favorite, and it makes the most sense to me as well. Are there any dissenting opinions? @emartinez-usgs @jmfee-usgs @cbworden
