### ISSUE TITLE
Origin detail FE region

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#1373]
in the origin’s Detalis section, the F-E Region never loads.
This is an example of the bug (see the attached image):
https://earthquake.usgs.gov/earthquakes/eventpage/us1000h5c4/origin/detail

![unnamed](https://user-images.githubusercontent.com/1726751/46365194-2ddfad00-c635-11e8-8095-4b2917a4f520.png)

**Comment by emartinez-usgs** [comment]
This is caused by the `ChangeDetectionStrategy.OnPush`. We need to bring in the change detection ref and trigger a change when updating the returned FE value. Not sure why the `@Input` doesn't trigger this already, my impression was that input changes should already trigger changes.

Anyway, needs fixing.

**Comment by jmfee-usgs** [comment]
I believe the `shared-fe-region` component should use a BehaviorSubject for its `fe` property, then update the value using `this.fe.next()`
