### ISSUE TITLE
Mobile bug

### ISSUE THREAD

**Issue by cswilson-usgs** [usgs/earthquake-eventpages#1384]
On origin detail, the data list cuts off on the right side of the screen. Maybe add horizontal scrolling class to it......

**Comment by ehunter-usgs** [comment]
This is a ViewEncapsulation.None issue. There is a too broadly scoped style being applied to the `.description-table`:
```
.description-table {
    /* width: 630px; */
}
```

**Comment by ehunter-usgs** [comment]
Just kidding, it turned out to be a `width` attribute instead of the appropriate `max-width`
