### ISSUE TITLE
Lat/lon display on maps

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/earthquake-eventpages#1396]
I think this is a small thing but there used to be a little display of lat/lon on the maps in the event pages. I found this to be very useful and so I'd like to request that those be added back in.

**Comment by cswilson-usgs** [comment]
@emthompson-usgs 
Are you referring to the exact lat/lng coordinates where the actual mouse is hovering, that get updated as the mouse moves around?

**Comment by emthompson-usgs** [comment]
The location of the mouse as it hovers, not when clicked.
