### ISSUE TITLE
Shakemap zoom animations

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/earthquake-eventpages#1403]
I personally don't like the little animation the maps do when you open them. It looks like the content starts off zoomed out and then zooms in to the correct location any time you open a map or switch between maps. I find it to be distracting and unnecessary. Others on shakemap team may want to weigh in on this: @wald-usgs @cbworden @kmarano-usgs?

**Comment by dslosky-usgs** [comment]
Hey @emthompson-usgs, the maps won't zoom anymore (as of #1398) now that we're using the shakemap product bounds to set the map limits!

**Comment by emthompson-usgs** [comment]
Okay, I didn't realize that. Thanks.
