### ISSUE TITLE
Improve social media sharing

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#1410]
- Remove Google+
- Improve Facebook

Consider the following:
https://developers.facebook.com/docs/sharing/webmasters/

**Comment by ehunter-usgs** [comment]
Also requries:
https://github.com/usgs/hazdev-template/pull/307

please reopen this ticket after merging, a new version of the hazdev-template will need to be deployed.

**Comment by ehunter-usgs** [comment]
Also, not entirely sure this is gonna work, but I don't know how to test it from on the network at work without deploying.

**Comment by emartinez-usgs** [comment]
Maybe consider: http://drib.tech/programming/dynamically-change-facebook-open-graph-meta-data-javascript

**Comment by emartinez-usgs** [comment]
Seems very doable. This will fix sharing from our page, but not necessarily the auto-posts to the USGS feed.

![Screen Shot 2018-10-15 at 5.53.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e4c62481dbf91d007acb83/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a37df117284f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee984690c72c43819adecd049b600ee208b48d4e5ee824ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e74952a2103064ef7f2431.png)

Generated with ...
```
FB.ui({
    method: 'share_open_graph',
    action_type: 'og.shares',
    href: 'https://earthquake.usgs.gov/earthquakes/eventpage/us1000haa3',
    action_properties: JSON.stringify({
        object: {
            'og:title': 'M 7.0 - 117km E of Kimbe, Papua New Guinea',
            'og:image': '... full url ...',
            'og:description': '... full description ...'
        }
    })
```

Can also use `og.likes` for slightly different results. Requires app registered to some USGS FB developer account.

**Comment by emartinez-usgs** [comment]
Or without an image it gets slightly different ...

![Screen Shot 2018-10-15 at 6.02.30 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e4c62481dbf91d007acb83/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a37ef112294f5c5f5ecc3c4a4356bcbbd671f3e57862804e0ee984690c72c43819adecd049b600ee208b48d4e5ee824ad2f42f67b6d5db1063474f4dcbed5727a19041c95df542e7495da5143161e5732431.png)

A representative image may be hard to come by in all cases. Personally I sort of like the non-image variant, but a USGS logo could do as well.

**Comment by ehunter-usgs** [comment]
Need to merge this PR, cut a tag, and then update earthquake-eventpages to use hazdev-ng-template@0.3.1
https://github.com/usgs/hazdev-template/pull/309
