### ISSUE TITLE
message for ios users

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#1438]
some message for old ios users who can't view the page.

**Comment by jmfee-usgs** [comment]
This branch shows a method to embed this content:
https://github.com/jmfee-usgs/earthquake-eventpages/tree/add-core-js-polyfills

We should include the following, in a helpful way, suggesting users upgrade to be able to view these pages:
- requires javascript
- requires a modern browser
- link to supported browsers ( https://angular.io/guide/browser-support )

**Comment by lisa-usgs** [comment]
I suggest:

To see our updated webpages, please upgrade your browser and make sure Javascript is enabled.
View supported browsers/versions. (link to https://angular.io/guide/browser-support)

**Comment by jmfee-usgs** [comment]
Thanks @lisa-usgs

**Comment by cswilson-usgs** [comment]
Is this strictly for old iOS users or is it for any user with javascript disabled?

**Comment by jmfee-usgs** [comment]
This is for any user that is unable to run the angular version.  Currently it has been reported by many ios 9 users, but there are likely old IE users (etc) that will see the same message.
