### ISSUE TITLE
SVG Image Map inside tablist

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#152]
Img tags inside of a tab list receive a margin-top of 1em. The svg image map that is overlaid on these images are off by 1em due to this margin.  

http://earthquake.usgs.gov/earthquakes/eventpage/ci37314320#impact_dyfi

**Comment by emartinez-usgs** [comment]
Change the margin to the first child of the panel instead of the img. Do not reference the .tablist-panel for this rule.

**Comment by jmfee-usgs** [comment]
This was fixed by #172
