### ISSUE TITLE
DYFI  form - fallback for failure of geolocation?

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/earthquake-eventpages#1524]
From the (recent?) increase of comments of failed submissions from users, I'm wondering if they're getting stuck with the geolocation part of the form. Is there a fallback when this portion doesn't work? Perhaps a note that directs users to the other geolocation methods (enter street address, or manually enter coordinates) after a certain period of time.

**Comment by llastowka-usgs** [comment]
We have a new form in version 1.21, lets see how that goes!
