### ISSUE TITLE
Ground failure

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#1539]
Should not state that there are alternate Ground Failure products.  Maybe was copied from another module? 
https://earthquake.usgs.gov/earthquakes/eventpage/us1000hyfh/ground-failure/summary

**Comment by jdbrown-USGS** [comment]
This is because it has 2 ground-failure products. The link takes you back to the impact summary. Should the impact summary have the ground failure product so you could link to the preferred and unprepared products? Should the link to the impact summary not be available at all?

**Comment by llastowka-usgs** [comment]
There was multiple GF products but one was deleted
