### ISSUE TITLE
Fix docker build

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#1609]
I believe the issue is the `usgs/node` image was updated to run as the underprivileged `usgs-user`; so the angular build process does not have permissions:
https://github.com/usgs/earthquake-eventpages/blob/master/Dockerfile#L14

Switching to the `root` user, changing ownership on `/earthquake-eventpages` to `usgs-user`, and switching back to `usgs-user`, should fix this problem.

**Comment by emartinez-usgs** [comment]
Better to just chown on the initial copy ...
```
COPY --chown=usgs-user:usgs-user . /earthquake-eventpages
```

**Comment by jmfee-usgs** [comment]
@emartinez-usgs nice, hadn't seen that option

**Comment by cswilson-usgs** [comment]
Fixed while updating Dockerfile in issue 1602
