### ISSUE TITLE
Show response page

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-eventpages#1630]
- Format as it was in the past
- Should replace page.

**Comment by cswilson-usgs** [comment]
For now, the form submit ticket (issue-1628) has the form submitting, and is checking for error responses - if there is an error caught in the http post call, the form component is emitting a FeltReportResponseErrorDetails object up to the tell-us component - need to implement changes in the tell us component to either show a success response, or an error response based on the type coming up from the event emitter. Currently if there is an error we are still showing a success response that just shows null values for everything

**Comment by cswilson-usgs** [comment]
This ticket has it's fix inside #1628
