### ISSUE TITLE
Interactive Map date-line issue

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#17]
If you look at an event near the date line, such as usc000mfm0

- the static summary map spans the world
- the interactive map plots cities on opposite sides of the world

This probably needs the same fix as the map in usgs/earthquake-latest-earthquakes for shifting markers left or right so they appear in the viewport.

**Comment by ehunter-usgs** [comment]
duplicate of #209 ?

**Comment by emartinez-usgs** [comment]
We no longer plot nearby cities on any map; instead we defer to cities listed in the map base-layer itself. The static map has been replaced with an "inert" dynamic map.
