### ISSUE TITLE
DYFI new version output corrupted

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/earthquake-eventpages#1721]
DYFI is getting corrupted data from the form. e.g.

0=inside&1=no&2=5&3=4&4=3&5=no_action&6=&7=&8=1+slight&9=0+rattled_slightly&10=0&11=0&12=0&13=0&14=_none&eventid=ak01934uh1xo&ciim_time=2019-03-09T23%3A39%3A58.850Z&location=%5Bobject+Object%5D&fldSituation_felt=1&fldContact_comments=Violent+initial+jolt+only+lasted+2-3+seconds%2C+immediately+dropped+off+and+slight+persistent+shaking+began+a+few+seconds+later%2C+lasting+about+a+minute.+We+were+on+the+ground+floor+of+a+two+story+home&ciim_mapLat=64.86071&ciim_mapLon=-147.82877&format=json&form_version=1.11&timestamp=1552337768&server=1b3ed37884be

1. Fields "0=...&1=...&2=..." looks like numerals are replacing the field names.
2. Location field value is being populated by "[Object object]"

**Comment by vinceq-usgs** [comment]
Eddie, looks like the "d_text" field has been changed to "damage" in the output, please change this back for compatibility

**Comment by ehunter-usgs** [comment]
reopening to fix `d_text` field

**Comment by vinceq-usgs** [comment]
Found a typo: "Very frigtened" -> "Very frightened"

**Comment by ehunter-usgs** [comment]
@vinceq-usgs when you expand the "use a map to verify location" map and you see the entire world, how did you get to that point? Are you on the "Unknown Event" DYFI form? That should be the only case where you are very far zoomed out. Otherwise you should see a 2 degree view with the map centered on the location you entered, or the event epicenter.

**Comment by ehunter-usgs** [comment]
> Eddie, looks like the "d_text" field has been changed to "damage" in the output, please change this back for compatibility

@vinceq-usgs, just to double check. This is the multiple select section at the end of the form that should be keyed with "d_text"?

**Comment by cswilson-usgs** [comment]
typo is fixed with #1685 PR

**Comment by vinceq-usgs** [comment]
> @vinceq-usgs when you expand the "use a map to verify location" map and you see the entire world, how did you get to that point? 

https://dev-earthquake.cr.usgs.gov/earthquakes/eventpage/unknown#tellus
I typed in my home address. However, I can no longer replicate this behavior. Looks like it is working as expected now.

> @vinceq-usgs, just to double check. This is the multiple select section at the end of the form that should be keyed with "d_text"?

Yes, and it should be output as a single string; multiple values combined with commas. e.g.

d_text=_none%2C_crackmin%2C_crackwallfew%2C_crackwallmany%2C_tilesfell%2C_crackchim%2C_crackwindows%2C_brokenwindows%2C_masonryfell%2C_majoroldchim%2C_majormodernchim%2C_tiltedwall%2C_porch%2C_move
