### ISSUE TITLE
ShakeMap Module update

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#1727]
@wald-usgs @cbworden @emthompson-usgs
Let me know if I miss anything here...

- Replace intensity contours with raster image download/intensity_overlay.png
- TOGGLE raster image with contours
- Add a download link

**Comment by jmfee-usgs** [comment]
Can I suggest doing only these features first, and moving the other more invasive changes to a separate issue?
- Replace intensity contours with intensity overlay
- Add download link beneath legend for PNG/JPG, with note about other downloads below
