### ISSUE TITLE
Use star for epicenter on shake-alert maps

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#1751]
Coordinate update to json with Glenn:
When feature has "icon" property set to "epicenter"

**Comment by jmfee-usgs** [comment]
possibly with existing epicenter-overlay.

**Comment by ehunter-usgs** [comment]
The `icon` property has been added to the epicenter features in the initial and final alerts for the `nc73143141` event (on dev)
