### ISSUE TITLE
Add shake-alert map tooltips

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#1752]
Show feature property "name" as tooltip. position at bottom center of circle/polygon.

Create a "hidden" (opacity 0.01) marker, then bind tooltip to marker:
```
marker.bindTooltip(
  feature.properties.name,
  {
    className: "tooltip",
    direction: "center",
    permanent: true,
    sticky: false
  })
```

Existing tooltip styles from ShakeAlert.  Adjust as needed to conform with rest of page.
```
 .tooltip {
  all: revert;
  font-size: 8px;
  font-weight: 700;
  background-color: none;
  border-color: none;
  background: none;
  box-shadow: none;
  fillColor: none;
  fillOpacity: 0;
  border: none;
  margin: 0px;
  fill: false;
 }
```

**Comment by ehunter-usgs** [comment]
The `name` property has been added to the `nc73143141` event on dev
