### ISSUE TITLE
Update text on shake-alert page

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1786]
This will require a copy of the post alert summary pdf (coming soon). Check the wording on the entire page, but in in the footnotes it looks like there is some missing text on the #3 footnote.

**Comment by ehunter-usgs** [comment]
![image](https://user-images.githubusercontent.com/1932750/62499957-b96c2200-b7a1-11e9-835b-0e22ee64ba6a.png)

**Comment by jmfee-usgs** [comment]
@ehunter-usgs remove footnote number 3
