### ISSUE TITLE
Shakemap Intensity observations should use circles

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#194]
Currently only DYFI network stations are shown as circles, intensity should also:

https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/modules/summary/ShakeMapStationLayer.js#L34

**Comment by jdbrown-USGS** [comment]
Intensity is also shown as circles.
https://github.com/usgs/earthquake-eventpages/pull/196

**Comment by jmfee-usgs** [comment]
#196 was merged
