### ISSUE TITLE
Static Maps Dateline Issue

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#209]
For events near the date line, such as usc000mfm0

The static map plots the event on the right of the trench, but the dynamic map plots it on the left of the trench.

This is likely a problem with the static map because the map is meant to be centered on the earthquake location, but for maps near the dateline, the "image" center does not align with the "map" center. The star is placed on the "image" center.

Potential solutions:
- Update static map plotting so star is in correct location.
- Update static map generation so image center always aligns with map center.

**Comment by llastowka-usgs** [comment]
Fixed with inclusion of SM contours?

**Comment by ehunter-usgs** [comment]
@emartinez-usgs  it looks like @llastowka-usgs is right. Is this fixed?

**Comment by emartinez-usgs** [comment]
Yes, since we implemented an "inert" dynamic map rather than the old static map solution I believe this is now not an issue.
