### ISSUE TITLE
Change CI link

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#213]
We would like to ask that this Contributor  link on the earthquake.usgs.gov event pages be pointed to:

www.scsn.org instead of www.cisn.org.  

Southern California Seismic Network, Caltech, USGS Pasadena, and Partners (CI)

**Comment by jmfee-usgs** [comment]
This should be updated in the anss-comcat project, which will be integrated into eventpages in the future:
https://github.com/usgs/anss-comcat

**Comment by llastowka-usgs** [comment]
see 222

**Comment by llastowka-usgs** [comment]
I don't know if that comment has anything to do with this issue so just change the links and text as requested. Thanks
