### ISSUE TITLE
Find a better place for impact-text

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#214]
Impact text products currently display below automatic tectonic summaries.  (hiding automatic tectonic summaries by default?)

> The Impact Text is in a strange place on the event pages... below the Tectonic Summary on the Summary page. I suggest higher on the page, since it's more important than the tectonic summary, or maybe even better, near the top of the Impact Summary page.
> See http://earthquake.usgs.gov/earthquakes/eventpage/us20002mgp#general_summary from an email from Bruce Presgrave: 
> "we added an Impact Text which said "First and smaller of 2 events about 5 seconds apart. Magnitude belongs with the second quake." Unfortunately, that text does not show in the ENS message, but it does show up on the web, although someone needs to scroll down past the Tectonic Summary to see it."

**Comment by ehunter-usgs** [comment]
Consider adding impact-text to executive summary page.

**Comment by ehunter-usgs** [comment]
consider adding the impact-text to the executive summary page.

**Comment by emartinez-usgs** [comment]
Impact text added to executive summary in #252. If this is acceptable, this issue can be closed.
