### ISSUE TITLE
Include regional waveform plots/links

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#215]
The waveforms page currently only links to IRIS, but some contributors have waveform plots or services and it would be useful to embed/link to these when possible.

**Comment by llastowka-usgs** [comment]
We would need to dig up these links to add this...

**Comment by jmfee-usgs** [comment]
Could consider showing Waveform type links on both scitech summary and waveforms page.

**Comment by jdbrown-USGS** [comment]
https://earthquake.usgs.gov/earthquakes/eventpage/us1000eu39#waveform

**Comment by ehunter-usgs** [comment]
Waveforms page is visible whenever you are not in scenario mode:
https://github.com/usgs/earthquake-eventpages/blob/master-pre-angular/src/htdocs/js/waveform/WaveformModule.js#L25
