### ISSUE TITLE
Add location and time to hypocenter summary page

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#219]
Or another way of representing differences between hypocenters at the summary level.
Not all information may fit on mobile screens, need to prioritize.

**Comment by ehunter-usgs** [comment]
My main additional comment is that the "Origin" summaries,
accessed by clicking the "Summary" and "Origin" tabs under the
"Scientific" heading, are not complete.  Currently the "Summary"
link under "Scientific" has a one-line "Origin" description
with the following five items:  magnitude, magnitude type,
depth, "Catalog," and "Location and Magnitude Data Source."
The "Origin" link under "Scientific" has multiple one-line
"Origin" summaries with these five items for each if more than
one organization has contributed a location and/or magnitude.
In my opinion, these one-line "Origin" summaries are incomplete
and somewhat confusing without the origin time and epicentral
coordinates.  While it is true that one can get this missing
information, and more, by clicking on the one-line "Origin"
description, it seems odd for the "Origin" summaries to have
less information about the "Origin" than the "Summary" page
under "General."  Also, including a complete 4-D description of
the hypocenter would make it easier to compare locations from
different organizations.

**Comment by emartinez-usgs** [comment]
Attached are some options for the preferred/review status information on the origin page. Thoughts?

![quality-statement](https://cloud.githubusercontent.com/assets/1726751/12145726/237f80da-b44d-11e5-973d-7f0b9c5ea735.png)

**Comment by ehunter-usgs** [comment]
I find the list format (with small icons) easier to consume. The sentences inside the alert element are understandable, but it takes me a little longer to comprehend the message. It almost feels like the alert message contradicts itself when I quickly scan the first option. Whereas the list option clearly delineates two distinct messages.

I would suggest using "the data below" or "this data" rather than "the data".

**Comment by vinceq-usgs** [comment]
I vote for the second option.
Some more suggestions:
- "This is the most preferred" and "This has not been reviewed" for
compactness
- Can "ml" be a hotlink to an explanation on different mag types?
- Depth uncertainty also needs units (km)

-- 
Vince Quitoriano (vinceq@usgs.gov)
USGS Did You Feel It?    http://earthquake.usgs.gov/earthquakes/dyfi
USGS ShakeMaps:        http://earthquake.usgs.gov/earthquakes/shakemap

**Comment by emartinez-usgs** [comment]
Progress can be seen here...

https://github.com/emartinez-usgs/earthquake-eventpages/tree/issue-219

Note: Some tests need updating and this is not meant to be complete yet. Some action items:

- Add more products to the scientific summary page.
- Convert impact summary page to extend the summary page and work similar to how scientific summary page works.
- Revert Summary/Details pages back to just details pages that can render a product type with a specific code. Drop the idea of summary/details pages.

**Comment by emartinez-usgs** [comment]
https://github.com/usgs/earthquake-eventpages/pull/272
