### ISSUE TITLE
Add lat lon to DYFI responses table

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#222]
NEIC needs lat lon of cities like in old DYFI table. They need to look up cities by lat lon.

**Comment by ehunter-usgs** [comment]
Add a latitude and longitude column at the end of the table. See the link below,
http://earthquake.usgs.gov/earthquakes/dyfi/events/ci/37280015/us/index.html

**Comment by llastowka-usgs** [comment]
relates to 242
