### ISSUE TITLE
Static Map Location Marker

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#224]
When the event occurs at high latitudes, the marker is incorrectly placed. See:

http://earthquake.usgs.gov/earthquakes/eventpage/us20002l0w#general_summary

**Comment by llastowka-usgs** [comment]
Now the marker is in the right place but it looks weird, but not much we can do. The text in the info box can probably be removed or changed to something like, due to the high latitude of this event, we recommend using Google Earth KML

**Comment by jmfee-usgs** [comment]
Replaced by https://github.com/usgs/earthquake-eventpages/issues/513
