### ISSUE TITLE
Create DYFI intensity vs distance plot 

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#227]
Using the same data file as interactive map (dyfi_geo.geojson), Vince will provide another json file that represents the predicted intensity curves.

Quitoriano, Vince added a comment - 2015-Jul-02 2:30 PM
I am now sending GeoJSON products for each DYFI event. They have the filename dyfi_plot_atten.geojson and dyfi_plot_numresp.geojson. These have the same data as the current attenuation-distance and responses vs. time graphs. Request that the web team use this data to create new interactive leaflet products to replace the older, static plots

**Comment by vinceq-usgs** [comment]
This is already being created, e.g.

http://earthquake.usgs.gov/realtime/product/dyfi/us1000424d/us/1448987742944/dyfi_plot_atten.geojson

There are two FeatureCollections with type:"estimated"

**Comment by vinceq-usgs** [comment]
So to clarify, the action plan right now is: web team will give me a template (json format) to populate?

**Comment by emartinez-usgs** [comment]
We will provide a template for you to review prior to our meeting next week. At the meeting we can discuss and refine the template. From there we will proceed with implementing the graph(s) assuming the agreed-upon file will be available.

**Comment by ehunter-usgs** [comment]
Hi Vince,

The attached file is what we came up with as a preliminary format. Most of
the fields should be pretty self explanatory from the example that we were
working with on the phone. If you have any questions don't hesitate to ask,
but we can always clear up any confusion when you are here next week.

http://earthquake.usgs.gov/earthquakes/eventpage/us1000424d#impact_dyfi

There are three properties that will help use determine how to plot the
different datasets in the dyfi_plot_atten.json file.  These properties are
boolean fields, that can be combined when necessary (see sample file).




* - "showPoints": true, *

Will plot the point data as a scatter plot



   - *"showLine": true,*

Will plot the connected point data as a line



   - *"showBins": true,*

Will check for a "stdev" value and plot the bin



If you combine multiple parameters, for instance:

*"showBins": true,*
*"showPoints": true*

The point dataset would be plotted inside the different standard
deviation bins.



On Thu, Dec 3, 2015 at 8:04 AM, Eric Martinez <notifications@github.com>
wrote:

> We will provide a template for you to review prior to our meeting next
> week. At the meeting we can discuss and refine the template. From there we
> will proceed with implementing the graph(s) assuming the agreed-upon file
> will be available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usgs/earthquake-eventpages/issues/227#issuecomment-161668048>
> .
>



-- 
Thanks,
Eddie Hunter

**Comment by ehunter-usgs** [comment]
```
{
  "title": "Intensity vs. Distance Plot",
  "xlabel": "Hypocentral Distance (km)",
  "ylabel": "Intensity (mmi)",
  "plots": [
    {
      "data": [
        {
          "x": 320.2,
          "y": 2.5
        },
        // ... rest of data points
      ],
      "legend": "All Reported Data",
      "showPoints": true // display dataset as a scatterplot
    },
    {
      "data": [
        {
          "x": 7.3,
          "y": 5.4
        }
        // ... etc
      ],
      "legend": "Atkinson-Wald 2007 Cent/EUS",
      "showLine": true // display dataset as a line
    },
    {
      "data": [
        {
          "x": 7.3,
          "y": 5.4
        },
        // ... etc
      ],
      "legend": "Atkinson-Wald 2006 CUS",
      "showLine": true // display dataset as a line
    },
    {
      "data": [
        {
          "x": 7.3,
          "y": 4.5,
          "stdev": 3.5
        },
        // ... etc
      ],
      "legend": "Median intensity +/-1 STDEV each dist bin",
      "showBins": true, // display dataset as binned data 
      "showPoints": true // also plot the point data
    }
  ]
}
```

**Comment by vinceq-usgs** [comment]
I am now producing these plots on ehpd-earthquake. e.g. http://ehpd-earthquake.cr.usgs.gov/product/dyfi/us100047zq/us/1450462335328/dyfi_plot_atten.json

**Comment by vinceq-usgs** [comment]
For reference, I wrote up the specs for the json data format here:
https://gitlab.cr.usgs.gov/dyfi-developers/dyfi/wikis/formats-intensity-vs-distance-data

**Comment by ehunter-usgs** [comment]
I used these events for testing:

Has new file dyfi_plot_atten.json:
http://localhost:8100/index.php?eventid=usb000ajek#impact_dyfi
http://localhost:8100/index.php?eventid=ci37286999#impact_dyfi:us_ci37286999
http://localhost:8100/index.php?eventid=ci37285175#impact_dyfi
http://localhost:8100/index.php?eventid=us20004hiu#impact_dyfi
http://localhost:8100/index.php?eventid=hv61128051#impact_dyfi
http://localhost:8100/index.php?eventid=ci37505432#impact_dyfi
http://localhost:8100/index.php?eventid=us100047zq#impact_dyfi

Falls back onto dyfi_plot_atten.jpeg:
http://localhost:8100/index.php?eventid=usb000ajek#impact_dyfi
