### ISSUE TITLE
Create an Executive Summary page

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#235]
Create a page with all of the preferred products for an event (mimic the executive summary tool).

@llastowka-usgs will attach an image!

**Comment by llastowka-usgs** [comment]
[nest.pdf](https://github.com/usgs/earthquake-eventpages/files/49921/nest.pdf)

**Comment by llastowka-usgs** [comment]
[M7.3KodariNepalEQ (2).pdf](https://github.com/usgs/earthquake-eventpages/files/50021/M7.3KodariNepalEQ.2.pdf)

**Comment by ehunter-usgs** [comment]
relates to #214
