### ISSUE TITLE
Shakemap maxmmi is missing

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#236]
On the impact summary and shakemap summary page, the mmi value is missing for US shakemaps. Check with the shakemap team to see if they are no longer sending maxmmi?

http://earthquake.usgs.gov/earthquakes/eventpage/us1000424d#impact_summary

**Comment by hasimpson-usgs** [comment]
Still found on some Shakemap products,  but they are the exception.
http://earthquake.usgs.gov/earthquakes/eventpage/us10003zgz#impact_summary

Will add -- when maxmmi is missing.

@cbworden any ideas why we most shakemap products no longer have a properties.maxmmi in them?

**Comment by jmfee-usgs** [comment]
This property is added by the shakemap indexer module, which should be configured on the servers.  Is there a specific pattern to the events where this is missing?

**Comment by hasimpson-usgs** [comment]
I can't see one.  I ran through the significant earthquakes until one came
up that actually had a maxmmi.   The first 8 did not.   Neither did the
next 2.   I thought the contributor might have something to do with it,  or
the order of the contributor,  but that doesn't look like a possibility
either.

On Wed, Dec 16, 2015 at 3:07 PM, Jeremy Fee <notifications@github.com>
wrote:

> This property is added by the shakemap indexer module, which should be
> configured on the servers. Is there a specific pattern to the events where
> this is missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usgs/earthquake-eventpages/issues/236#issuecomment-165259791>
> .
>



-- 
Hal Simpson
IT Specialist
USGS Geomagnetism Program
Office:303-273-8459
Email:hasimpson@usgs.gov

**Comment by emartinez-usgs** [comment]
It looks like US shakemaps are not getting the property. If you look at a CA event with a shakemap produced by NC or CI, then the MMI seems to be there.

**Comment by hasimpson-usgs** [comment]
I may be misunderstanding,  but this is a US shakemap.  
http://earthquake.usgs.gov/earthquakes/eventpage/us10003zgz#impact_summary

**Comment by cbworden** [comment]
Eric/Jeremy,

Where do you get the maxmmi? If it’s from info.xml, I’ve updated the structure of info.xml along the lines we discussed (though this may not be the final version). But if your source is info.xml, then it’s likely that your system can’t find the parameters in the updated file for recent events. I wasn’t enthusiastic about updating info.xml in this semi-final state, but it was necessary for some work we are doing. Our version will be different from that of the RSNs until they update to the latest version of ShakeMap. The new version has a “version=2.0” attribute in the “info” tag. Earlier versions don’t have a version attribute.

Bruce

**Comment by emartinez-usgs** [comment]
MMI properties are summarized during indexing. Relevant source code can be found here:

https://github.com/usgs/pdl/tree/master/src/gov/usgs/earthquake/shakemap

Particularly of interest are the
 - ShakeMapIndexerModule.js
 - ShakeMap.js
 - InfoXMLHandler.js

**Comment by jmfee-usgs** [comment]
Hello,

We are currently parsing the maxmmi property from the old style info.xml, and any changes to that file would require development on our end before they are supported.


As a more flexible alternative, as opposed to the indexer module currently being used, you can specify properties on the command line when sending the products.  This is the preferred approach particularly if you are adding new features and can support this.

You can see the properties that are currently extracted from grid.xml and info.xml on this page:
http://ehppdl1.cr.usgs.gov/userguide/products/shakemap.html


Thanks,

Jeremy
