### ISSUE TITLE
Station List Loading Error

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#239]
The station list for this event errors out while loading,
http://earthquake.usgs.gov/earthquakes/eventpage/us1000424d#impact_shakemap

**Comment by cbworden** [comment]
I've revised the ShakeMap code to remove backslashes from the value portion of key-value pairs. That should resolve this particular issue. I've deployed the fix to GSM but, as usual, it will be some time before the RSNs update their code.
