### ISSUE TITLE
Update search form

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#243]
This will require more discussion, but the general idea:
 - Create simplified form
 - Hide more advanced options
 - List selected search parameters under the search button

**Comment by vinceq-usgs** [comment]
More suggestions:
- userfriendly time search (last 24 hrs, last 7 days)
- search by location string e.g. Oklahoma
- for power users, search field instead of multiple buttons e.g. "mag >= 6 and response >= 1"

**Comment by hasimpson-usgs** [comment]
See #264
