### ISSUE TITLE
Create DYFI responses vs time plot

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/earthquake-eventpages#263]
Create new plot for responses vs time using JSON format file. This is analogous to the intensity vs distance plot currently under development. This format may need discussion.

JSON format data spec here:
https://gitlab.cr.usgs.gov/dyfi-developers/dyfi/wikis/format-responses-vs-time-data

The file is already being produced on the dev pages, e.g.
http://ehpd-earthquake.cr.usgs.gov/product/dyfi/us10004a1v/us/1451344134057/dyfi_plot_numresp.json

**Comment by ehunter-usgs** [comment]
Use DYFIIntensityGraphView.js as an example for how to implement this.

**Comment by ehunter-usgs** [comment]
@vinceq-usgs I am working on this ticket and I was wondering if you could update your output for dyfi_plot_numresp.json I just noticed that your float/number values are listed as strings:
 - `preferred_conversion`
 - `datasets.data.x`
 - `datasets.data.t_seconds`

Thanks!

**Comment by vinceq-usgs** [comment]
Eddy, I updated this for event nc72826161 (should be revised shortly?) and it will be fixed for all subsequent events.
