### ISSUE TITLE
link to timeseries plots where applicable

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#275]
Possibly the phases table for now?

http://service.iris.edu/irisws/timeseries/1/query?scale=AUTO&net=IU&sta=ANMO&loc=00&cha=BHZ&starttime=2010-02-27T06:30:00&endtime=2010-02-27T10:30:00&output=plot&width=600&height=300

**Comment by hasimpson-usgs** [comment]
Link the channel column when SNCL and starttime are known.
