### ISSUE TITLE
Update source attribution

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#278]
For discussion, I propose any time we list source information for a product we should include contributor and any author(s).

For origin/phase-data products, this would include:
- product source
- "origin" source ("origin-source" property)
- "magnitude" source ("magnitude-source" property)

For focal-mechanism/moment-tensor products, this would include:
- product source
- "beachball" source ("beachball-source" property)

Codes should appear in the orders listed above and should not contain duplicates.

**Comment by jmfee-usgs** [comment]
Authors are independent of catalog.  There may be many authors of a given piece of information, but it only belongs to one catalog.  Any information that belongs to multiple catalogs is represented with a (potentially duplicate) submission to each catalog.

**Comment by ehunter-usgs** [comment]
create a method in the Attribution class called getProductAttribution(product) that returns a DOM element. Currently for use in the "source" column on the summary tables.
