### ISSUE TITLE
change tectonic summary for sonic booms or other non-eq event types 

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#280]
The tectonic summary is not really relevant for an event page for a sonic boom or other non-earthquake events (like boat crash). Consider removing and/or creating custom content based on other event types.

**Comment by ehunter-usgs** [comment]
Remove tectonic summary where event type is sonic boom.

**Comment by emartinez-usgs** [comment]
This will be resolved as part of #308.
