### ISSUE TITLE
Change how page title is generated

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#281]
from @paulearle :+1: 

When sending a "title" property on the preferred origin product, it would be nice if that were used as the full event title on the event page. That is, do not prefix with the magnitude or event type as would otherwise be done.

This should not affect how titles are generated in most cases, but only when sending an explicit title property on an origin.

**Comment by jmfee-usgs** [comment]
This risks the title falling out of sync with the actual magnitude for the event.

**Comment by emartinez-usgs** [comment]
That could happen. The use case however is to remove the magnitude from the title altogether.

**Comment by hasimpson-usgs** [comment]
Depends on changes to the earthquake-event-ws first.
A title product could have 2 modes,  one that only replaces the location(Title), and one that replaces location, magnitude, and event type(Full Title).

**Comment by jmfee-usgs** [comment]
Moved to earthquake-event-ws, event pages display data from the web service and feeds.
