### ISSUE TITLE
Change how DYFI responses table download works.

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#283]
Remove download button.  
Put a link to "Download DYFI responses" url comes from DYFI product content cdi_zip.txt 

From a user. he was happy to have the lat/lon in distinct fields. 
Please change what's in the Distance column back to a number, like it used to be. It doesn't need to have "km" next to every entry. If you want to add (km) to the heading that's OK, but don't put it into the data fields. Spreadsheets are easier to do things with actual values instead of text. Having "km" in every Distance cell requires an extra step of doing a global replace to eliminate all the instances of "km" in order to convert them into a number.

**Comment by hasimpson-usgs** [comment]
For now, style out the Download button in the DataTable using css, we've added an issue to webutils, to make the button optional.  
We might want to be more specific on the link Text.  Maybe Raw or Unsorted,  depending on where we position the link on the page.

**Comment by jmfee-usgs** [comment]
"Download DYFI Responses as CSV (SIZE)" above the sort options
