### ISSUE TITLE
create ShakeMapStationListView class

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#295]
in js/shakemap folder

Should render contents of ShakeMap details station list tab, from existing page https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/modules/impact/ShakeMapPage.js#L267

**Comment by ehunter-usgs** [comment]
- Import all the needed CSS, Station List should look how it used to look. Some things I noticed:
 - abbreviations should be on it’s own line
 - mmi should have background color
 - There should be a max width on list items
 - more padding on list items (creates space for table in collapsed details section)
- Content message isn't really accurate, this tab won't exist unless stationlist.json exists. Maybe change it to, "Could not load the station list."
- Remove commented code `VAR STATION_LIST = ...`
- Add comments for methods that have none
- Update comments that were for the DownloadView
- Use the formatter where possible (see buildStationList method Line 70-77)
- Add ImpactUtil if it's going to be used, don't reference anything in the "modules" directory, this is going away
- In _this.onSuccess you don't have to wrap the station list in another div, this should be enough:
```_this.el.innerHTML = _this.buildStationList(responseText);```
This will probably cause some of your tests to break, do something like this:
```
    it('should create a list', function () {
      /* jshint -W030 */
      expect(view.el.querySelectorAll('.shakemap-stations > .station').length).
          to.equal(0);
      /* jshint +W030 */

      view.onSuccess(responseText, xhr);

      /* jshint -W030 */
      expect(view.el.querySelectorAll('.shakemap-stations').length).to.not.
          be.null;
      /* jshint +W030 */
    });
```
- Drop the "new" keyword, when creating the accordion, that was the old way of doing things.

**Comment by jmfee-usgs** [comment]
please rebase

**Comment by jmfee-usgs** [comment]
- In the tests, querySelector (singular) returns either an element or null instead of an array

For discussion:

- units in station details table headers, should they appear in cells with the values?
- Much of ImpactUtil seems like it should be in Formatter
- docstring formatting:
```
/**
 * Brief method description
*
* [more details if needed]
*
* @param param1 {Type}
*     param1 description
* [more @params, no blank lines]
* @return {Type}
*/
```

**Comment by emartinez-usgs** [comment]
Regarding discussion:
- Units should appear next to each value. That is NIST.
- Yes, ImpactUtil and Formatter are quite redundant.
- I think a blank line between the `@param` and the `@return` statements (IMO). But no blank lines between each `@param`.

**Comment by jmfee-usgs** [comment]
- the global variables `MMI_ARRAY` and `MMI_COLORS` should be underscore prefixed, and appear in alphabetical order (after _DEFAULTS)
- rename `getMmiColor` and `translateMmi` to `mmiColor` and `mmi` for consistency with other formatter methods.
- add unit tests
- add and use the following Formatter method:
```
/**
 * Format an intensity value.
 *
 * @param intensity {Number}
 *     numeric intensity value.
 * @param text {String}
 *     default ''.
 *     content added following the formatted intensity value.
 * @return {String}
 *     formatted intensity.
 */
_this.intensity = function (intensity, text) {
/* TODO: return something like:
<span class="mmi mmiX">
  <span class="roman"><strong>X</strong></span>
  <abbr title="Modified Mercalli Intensity">mmi</abbr>
</span>

where the 'abbr' would be passed in as the text parameter.
*/
}
```
- '&nbsp' needs a semi-colon
https://github.com/usgs/earthquake-eventpages/pull/365/files#diff-5d8dda80254452913d8c695e29940593R301
