### ISSUE TITLE
create GeoserveNearbyPlacesView class

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#301]
This will extend NearbyPlacesView, and will know how to access the Geoserve web service to gather nearby places information. make sure it fixes the problem below. 

When an event does not have an explicit nearby-cities product, it defaults to using Geoserve results for the list of nearby cities. In this case, output information is incorrectly formatted.

Expect:
Xkm (Ymi) DIR of City, State

Actual:
Xkm (Ymi) ?azgap? of City

Note: This only affects events without a nearby-cities product.

**Comment by emartinez-usgs** [comment]
- Need to keep `.innerHTML` on GeneralSummaryModule.
- Need to deal with azimuth = 180 on backAzimuth function.
- Needs tests for backAzimuth function.
- Alphabetize imports in GeoserveNearbyPlacesView
- Make GeoserveNearbyPlacesView extend the regular NearbyPlacesView
  - The `onSuccess` method should be a `Util.compose` with the original method. The custom implementation just augments the data structure so the regular NearbyPlaces view will be able to render the data.
  - Remove duplicate methods.
- Change `_url` configuration to include the places.json endpoint but do not include query string parameters. Instead use the `data` parameter on the Xhr call.
- Set a default geoserve url in the class itself.
-

**Comment by jdbrown-USGS** [comment]
- added .innerHTML in GeneralSummaryModule
- Fixed backAzimuth and added test.
- Alphabetized imports in GeoserveNerbyPlacesView
- GeoserveNearbyPlacesView extends NearbyPlacesView
- Changed _url configureation to include the places.json 
- Set default geoserve url in the class itself.
