### ISSUE TITLE
create ShakeMapInfoView class

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#302]
To display info.json.  More details to follow.

**Comment by ehunter-usgs** [comment]
Link to the google doc that describes the format:
https://docs.google.com/document/d/1JkWXnEDDzsXtBO2hNdImb8OpLAU4Oz7Er-rYgGKXqqI/edit?ts=56d5cbd7

**Comment by hasimpson-usgs** [comment]
Talk to Jeremey about details.

**Comment by emartinez-usgs** [comment]
Needs tests.

Tables should have units with values. Degrees (symbol), km, g (%g) ? As a policy, units accompany the values and are not in the header (and using header units doesn't even make sense in some of the tables).

**Comment by emartinez-usgs** [comment]
Event us20005cx1 has info.json on dev.
