### ISSUE TITLE
create GeneralModule

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#308]
Display region information, possibly merge with executive summary?

**Comment by emartinez-usgs** [comment]
Make this a carbon-copy of the existing general (default) page.

**Comment by emartinez-usgs** [comment]
Suppress tectonic summary content (both auto and manual) when event type is sonic boom.

This relates to #280.

**Comment by emartinez-usgs** [comment]
- Tectonic summary should not be in a collapsable accordion
- Tectonic summary is missing image
- Downloads is missing
- Missing general-header content
- Should prefer tectonic summary product and fall back to geoserve.
- Needs tests for GeneralSummaryModule

**Comment by emartinez-usgs** [comment]
Getting error that `_this` is null at certain times. To reproduce:

- Go to event page general summary module.
- Open interactive map.
- Refresh page with map still open
- Close interactive map.

Console will cause errors, though page subsequently renders correctly.
