### ISSUE TITLE
create ShakeMapSummaryView

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#317]
summarize a shakemap product for executive summary page

**Comment by ehunter-usgs** [comment]
Q: I thought we ennumerated the ShakeMap summary columns. Should I just be creating the summary view with the fields that we already summarize, just in the new style (table).

**Comment by jmfee-usgs** [comment]
A: that is for the IntensitySummaryModule; this summary view is what would be displayed on the executive summary page and probably requires more discussion before implementation.
