### ISSUE TITLE
create OriginView

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#320]

**Comment by jmfee-usgs** [comment]
- OriginView should have a tablist, similar to ShakeMapView, the first tab is the existing origin detail table; second tab will be phases; third tab is magnitudes view
- css rules for hypocenter-phase and network-magnitude aren't needed; magnitude view already has all the rules it needs in a separate file, phases will have own file.
- minimum distance, azimuthal gap, etc, could use _formatter.angle and _formatter.distance methods
- Travel Time Residual units should be "s" for seconds.
- add a destroy method, and call from test

**Comment by emartinez-usgs** [comment]
- Use origin module to provide the configured geoserve url as a "url" property to the origin view.
- Update origin view to just use `options.url` with a reasonable default provided in _DEFAULTS.
