### ISSUE TITLE
create FocalMechanismView

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#326]

**Comment by emartinez-usgs** [comment]
- Creating double `<section class="moment-tensor-view">` containers. This doesn't seem necessary. (It's actually an issue with MomentTensorView but w/e).
- Unused variable `tensor` in example JS.
- Does it matter the classes for this view still reference `class="moment-tensor-view"`
- This view is getting an inappropriate "Moment Tensor" title above the contributor information table.
  - Perhaps override `getTitle` method?
