### ISSUE TITLE
create WaveformModule

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#328]

**Comment by jmfee-usgs** [comment]
- The module title should be "Waveforms"

- the data and xhr test variables, and before, appear to be unused.
- rendersContent test isn't valid...  instead of stubbing onSuccess amd calling renderContent directly, stub parseIrisEventId to return the eventId then call onSuccess and verify onSuccess called renderContent with the event id that was "parsed"

**Comment by jdbrown-USGS** [comment]
- Changed title.
- Fixed test

**Comment by emartinez-usgs** [comment]
- Need a "Back to Scientific Summary" link in the header.
- Put a little spacing between the two paragraphs.
- Single quotes (contractions) should use `&rsquo;` or similar character.
