### ISSUE TITLE
create FiniteFaultView

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#330]
This should extend TextProductView via a configurable contentPath parameter. Talk to Jeremy for more information.

**Comment by jmfee-usgs** [comment]
TextProductView (and thus FiniteFaultView) need a destroy method

**Comment by emartinez-usgs** [comment]
Added destroy method to TextProductView. There is nothing additional to destroy in FiniteFaultView at this point.
