### ISSUE TITLE
create DYFIIntensityGraphView

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#334]

**Comment by jmfee-usgs** [comment]
The x axis scale has a lot of overlapping labels, is that expected?  If so re-close this issue.

**Comment by ehunter-usgs** [comment]
The x-axis scale was an issue that already existed. No good solution has been found. We could try using a linear scale, it changes the shape of the curve obviously, but it seems to have less overlap on the x-axis scale.

**Comment by jmfee-usgs** [comment]
I don't think this works as expected.  Implement a test that adds a subview and calls destroy to verify.

1) graph.views is a collection, not an array, so it doesn't have a forEach method.
2) if in the future the graph destroys views in its collection, it may cause problems.  I recommend something along these lines:
```
views = graph.views.data();
graph.views.reset([], {silent: true{);
views.forEach(function (v) {
  v.destroy();
});
graph.destroy();
```

**Comment by jmfee-usgs** [comment]
It definitely needs to use a log scale, pretty sure that was a requirement, but we can manually assign which ticks to label.  I'll add an issue to the backlog to address that.
