### ISSUE TITLE
create DYFIFormView

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#335]
This is the form, not the dialog that wraps the form.

**Comment by emartinez-usgs** [comment]
- _DYFIFormView.scss should not specify additional `@import` declarations. Instead, add each of these to the event.scss main file.
- TextQuestionViews.scss should be _TextQuestionView.scss

TextQuestionView
- TextQuestionView should accept a model and the model should have a value, label and other attributes.
  - Render method should be created and should update the input value.
  - On input change should just set the model value.

DYFIFormView
- Read the url property off the options object during initialize and store and use as _url on the instance.
  - Do not keep a reference to the input options as _options.

- LocationControl (and dependent classes) all need to be updated to use a global `L` for leaflet.
- hazdev-location-view build process needs to be changed to not bundle Leaflet into package
  - Use a /lib/leaflet-X/... (version specific) site-wide copy of leaflet. Locally this will need to be copied out of node_modules into htdocs/lib folder.
- hazdev-location-view examples need to be updated to include leaflet.js
- hazdev-location-view tests need to be updated to include leaflet.js and global `L`.
