### ISSUE TITLE
create DYFIResponsesView

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#336]
This is all of the content inside the DYFI Responses tab.

**Comment by jmfee-usgs** [comment]
- global formatter object should be named `_FORMATTER`.
- instance variable `_formatter` is not used; _initialize method appears to not be needed
- `_this.onToggleButtonClick` does not need to be bound to _this (it already effectively is...)
- implement a destroy method that removes event listeners
- button, responseTable, and responseTableEl can be private variables and no longer need to be attached to _this

**Comment by jmfee-usgs** [comment]
- toward the end of buildResponsesCollection, only call locationName.split once (i.e. `locationName = locationName.split('::')`)
- destroy should check whether `_button` and `_responseTable` are not null before calling methods.
- destroy should also set _responseTableEl to null.
- in onSuccess, separate the var declaration and assignment; or remove variable and pass directly into DataTable call

**Comment by jmfee-usgs** [comment]
- add _initialize method to set vars to null, only declare in the var statement.
- in destroy, if setting a var to null you don't need to check if it's null first
- do not use `new` keyword when creating Collection
- make sure collection is either destroyed by DataTable, or switch responses to an instance variable and destroy manually
