### ISSUE TITLE
Add support for rewrites

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#339]
During url parsing, map existing URLs, for example: 

general_summary
to
general

This is in the EventPage

**Comment by jmfee-usgs** [comment]
- Add params to redirect url
https://github.com/usgs/earthquake-eventpages/pull/414/files#diff-d830acaa6c242171a79ca6f7656ccb77R414

- It doesn't seem like _parseLegacyHash needs to return a `redirect` property, the module value is already the redirect...
