### ISSUE TITLE
dyfi submit button

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#452]
appears green, even when disabled.  should be gray until enabled.

**Comment by jmfee-usgs** [comment]
also

- increase Felt Report header size
- move omb to top right

**Comment by emartinez-usgs** [comment]
button gets properly disabled. there should be an issue in the template to make disabled buttons look more disabled. don't try to fix that here.

**Comment by ehunter-usgs** [comment]
Cannot reproduce. Not sure what was happening yesterday...

**Comment by emartinez-usgs** [comment]
Button styles appear correct, however the other issues on this ticket (see @jmfee-usgs comment above) still need to be addressed.
