### ISSUE TITLE
DYFIForm Scroll Jumping in Chrome

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#463]
Reproduce
- Open the DYFIForm for an event.
- Scroll the form so a field option that was not initially visible is now visible.
  - Do not scroll all the way to the bottom of the form.
- Click that newly visible field

Actual Result:
Form scrolls seemingly randomly.

Expected Result:
Form should not scroll at all.

This seems to only affect Chrome.

**Comment by jmfee-usgs** [comment]
Moved to template pr, package.json may need to be updated:

https://github.com/usgs/hazdev-template/pull/237

**Comment by ehunter-usgs** [comment]
Merged into hazdev-template. Need to update dependencies.
