### ISSUE TITLE
Lock-in Dependency Versions

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#464]
- Look at package.json and see all the packages that are using the git/HEAD for a project.
- Finalize each dependent project and release an updated version.
- Update package.json to use the fixed version of each dependency.

**Comment by ehunter-usgs** [comment]
Versions:
- hazdev-d3, unchanged (v0.2.1)
- hazdev-leaflet, changed (v0.1.2)
- hazdev-svgimagemap, changed (v0.0.7)
- hazdev-webutils, changed (v0.1.8)
- quakeml-parser-js, changed (v0.0.3)

**Comment by ehunter-usgs** [comment]
This may need to change after cross-browser testing, so I am leaving it "in progress"

**Comment by ehunter-usgs** [comment]
Update:
- hazdev-template (tag a new version with form updates)
