### ISSUE TITLE
Logos in Banner

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#478]
Are we no longer adding contributor logos into the banner?

**Comment by jmfee-usgs** [comment]
I merged the pr, but this would be better implemented in a separate method like `onAttributionReady` (instead of anonymous function in initialize) which could then check if there is an event and preferredOrigin product instead of keeping that reference around...

**Comment by ehunter-usgs** [comment]
@jmfee-usgs is the new PR what you were talking about?

**Comment by jmfee-usgs** [comment]
yes, thanks
