### ISSUE TITLE
Attribution isn't working

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#482]
Same with KML download. 

I am running this locally, but attribution isn't pulling in the full name and link to contributor information because it cannot find index.json.php (looking on localhost). It is also looking locally for the KML download, is this supposed to be redirected to OFFSITE_HOST?

**Comment by ehunter-usgs** [comment]
Is this just something we ignore because it will work on dev and prod?

**Comment by jmfee-usgs** [comment]
You could add a proxy section in gruntconfig connect for the /data/comcat/ and /scenarios/ urls
