### ISSUE TITLE
Add data to DYFI popup

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#503]
Migrating from https://github.com/usgs/earthquake-latest-earthquakes/issues/50

I am adding a 'location' property to each entry of the file 'dyfi_geo.geojson' for each event. This location needs to be added to the popup that comes up when a user clicks on one of the DYFI locations on the Interactive Map.

Example:
{"features":[{"geometry":{"coordinates":[[[-150.11038,62.26454],[-150.09115,62.26414],[-150.09028,62.2731],[-150.10952,62.2735]]],"type":"Polygon"},
"type":"Feature","properties":{"location":"Talkeetna","nresp":1,"name":"UTM:(5V 0650 6907 1000)","cdi":3.4,"dist":48}},{"geometry":{"coordinates":[[[-150.08682,62.30896],[-150.06755,62.30855],[-150.06668,62.31752],[-150.08595,62.31792]]],"type":"Polygon"},
...

**Comment by vinceq-usgs** [comment]
This is working right now, will keep current functionality.

**Comment by emartinez-usgs** [comment]
It looks like Vince worked this into the `name` property and a `location` property is no longer included in the geojson file(s). Because of this, along with Vince's comment, I'm closing this as won't fix.
