### ISSUE TITLE
DYFI Intensity vs Distance plot axis plotting

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/earthquake-eventpages#509]
DYFI Intensity vs Distance plot:
For events with only 1 response plotted, the x axis is missing axis ticks or tick labels.

e.g.
http://dev-earthquake.cr.usgs.gov/earthquakes/eventpage/us10005df5#dyfi

**Comment by hasimpson-usgs** [comment]
See hazdev-d3 pull https://github.com/usgs/hazdev-d3/pull/17
