### ISSUE TITLE
Magnitude table render bug

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#510]
Magnitude elements may have a creationInfo without an agencyID.  The view should check whether agencyID is defined, and otherwise use the default value:
https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/js/origin/MagnitudesView.js#L230

We should also update Attribution to handle empty values more gracefully.

**Comment by jdbrown-USGS** [comment]
https://github.com/usgs/quakeml-parser-js/pull/7
