### ISSUE TITLE
submit button gets greyed out on DYFI form

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#514]
if you click on Yes or No (2nd question) and then do the location (1st question), the Submit button remains grayed out.  It you go back and click on yes or no it becomes active again.

**Comment by hasimpson-usgs** [comment]
In onFormChange,  a document.querySelector call is used to find the submit button. 
When locationView is used,  the submit button doesn't exist at that time, so the call fails,  and the submit button can't be set.  

It looks like if location is the last thing set,  the submit button will never be released.
