### ISSUE TITLE
Duplicate Links in "For More Information" section on General Summary page

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#517]
It would appear that links are being duplicated when multiple origin products exist for an event. The multiple origin products are causing multiple geoserve products to be generated. 

http://earthquake.usgs.gov/earthquakes/eventpage/ci37374687#general

**Comment by emartinez-usgs** [comment]
https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/js/general/GeneralSummaryModule.js#L241
