### ISSUE TITLE
OriginPin

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#551]
Create product-specific pin for origin products.

**Comment by emartinez-usgs** [comment]
- Make magnitude badge smaller (about the size of the impact bubbles in old event summary).
- Simplify markup.
- Review status should not be bold but should be all uppercase.
- Review status should be "MANUAL" or "AUTOMATIC".
- Review status does not need a label.

- Try to avoid `.classname > tagname` selectors. Prefer to add a class to the child tag name and target that directly.
   - Use OOCSS naming conventions
```css
/* Less good */
.parent {
  > .child {
  }
}

/* Preferred */
.parent {
}
.parent-child {
}
```

- Integrate into ExecutiveSummaryView

**Comment by jdbrown-USGS** [comment]
- Made magnitude badge more like impact bubbles
- Changed markup
- Change review status to not be bold and updated to be either MANUAL or AUTOMATIC
- Removed review status label
- Updated Class names.

**Comment by emartinez-usgs** [comment]
Default module should be an actual `OriginModule` and not a stub. This is better because if the module ID changes in the future, the pin will not break.

**Comment by emartinez-usgs** [comment]
Reformat content...

- Label "Review Status"
- Use text "Reviewed" or "Automatic"
  - Do this everywhere we display review status (i.e. Origin details page)
- Add more key-value data such as lat, lng, depth, time
- Consider a "pirate" font care of @llastowka-usgs 
- Move pin down in ExecutiveSummary order to match left-navigation ordering.

**Comment by emartinez-usgs** [comment]
- Remove "Location" header and content from pin.
- Add "Magnitude" header with content containing magnitude value and magnitude type.

**Comment by jmfee-usgs** [comment]
There's a potential bug for review status, if the product property review-status is null then toUpperCase will generate an error:
https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/js/origin/OriginPinView.js#L50

Also, should the origin pin attributes be alphabetized? (depth, magnitude, review status, time)

**Comment by emartinez-usgs** [comment]
I don't feel alphabetizing is necessary. A logical order is fine, especially when the list of attributes is so short.
