### ISSUE TITLE
FocalMechanismPin

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#554]
Create product-specific pin for FocalMechanism products. Debatable. There is no "preferred" focal mechanism so which would be featured on an executive summary?

**Comment by jmfee-usgs** [comment]
All from the preferred contributor, I believe there will be at most two maybe a mobile-two-up or similar that displays both beachballs?

**Comment by jmfee-usgs** [comment]
Currently only showing one FM from preferred contributor, all from the preferred contributor are considered equally valid.

An example event with 2 FMs is nc72659061.

**Comment by emartinez-usgs** [comment]
On this page we will only show one FM regardless.
