### ISSUE TITLE
RegionalInformationModule

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#555]
Module for displaying regional (i.e. NOT event-specific) information. This page should render much of the content from the geoserve web service (nearby places, admin regions, fe regions, etc...) as well as generic tectonic summaries.

Note: Many of the required sub-views were previously implemented in the "js/general" folder.

**Comment by emartinez-usgs** [comment]
- Use new nearby places format similar to what is found on /ws/geoserve/
- Use a subtitle under "Nearby Places" header to explain with the direction is "from" or "to" a reference location (i.e. event epicenter).
  - Event epicenter should remain fixed and directions should be relative to that.

**Comment by emartinez-usgs** [comment]
- Add historic seismicity overlay to the map
- Add population density overlay to the map
- Make map clickable to bring up interactive map.
  - Should have historic seismicity and population density overlays enabled when this occurs.

**Comment by jmfee-usgs** [comment]
Use the actual HistoricSeismicityLayer being added in #557

**Comment by emartinez-usgs** [comment]
Done as part of #620
