### ISSUE TITLE
History Seismicity Layer

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#557]
Add a history seismicity layer to the interactive map. This should be off by default and should use the ArcGIS map service from /arcgis/rest/services/eq/catalog_2015/MapServer

This layer currently does not need to support any interactions. We can iterate with @gsmoczyk and other stakeholders on layer styling as needed.

**Comment by emartinez-usgs** [comment]
Web service is not yet ready.

**Comment by emartinez-usgs** [comment]
Tile layer is now available. @gsmoczyk will publish soon.

**Comment by emartinez-usgs** [comment]
Not done yet, but depends on this PR which could be merged in order for this ticket to move forward...

https://github.com/usgs/hazdev-leaflet/pull/18

**Comment by jmfee-usgs** [comment]
Merged usgs/hazdev-leaflet#18

**Comment by jmfee-usgs** [comment]
still some unused variables:
https://github.com/usgs/earthquake-eventpages/pull/618/files#diff-136aa637d0500c8536e69aff4339ecefL61
