### ISSUE TITLE
RecentSeismicity Search

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#558]
Add a link to the left navigation in "General" section for "Recent Seismicity". This link should take the user to the map and list with recent seismicity. Iterate with an event coordinator for what constitutes "recent seismicity". As a starting point, try +/- 30 days from current event. Circle search centered on event epicenter with a radius of 500 km. If possible, highlight the current event on the map/list interface.

**Comment by jmfee-usgs** [comment]
I asked Paul for suggestions on parameters:

- location = 150km radius around epicenter
- min magnitude = (floor(mag) - 3)
- time = +/- 3 weeks

**Comment by jmfee-usgs** [comment]
Updated location to 250km radius, set minimum minmagnitude to 1.
