### ISSUE TITLE
DYFIFormPin

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#578]
create a pin for the DYFI Tell Us page

**Comment by emartinez-usgs** [comment]
Maybe some explanatory text like the Tsunami pin.

> Complete a questionnaire about your experience during this event and contribute to the DYFI citizen science product.

**Comment by emartinez-usgs** [comment]
Just some ideas, feel free to re-close this ticket if you disagree...

- Numbers seem "squished" to me, maybe more left/right padding?
- Background gradient seems heavy to me.
- Maybe left-pad small numbers with zeroes? When felt reports are single-digit (or even double-digit), the "odometer" look and feel is lost.
  - Our widest felt event has felt reports in the 100k range. It is unlikely we will have anything in the millions, but there seems to be room.
- Is "Tell Us!" the best text we can use for the title?
- Should the contributor still be "US" or should we say "Citizen Science" or "Public Contributions" or something along those lines?

Attached example of what some soften styles might look like.
![screen shot 2016-07-08 at 7 31 57 am](https://cloud.githubusercontent.com/assets/1726751/16689274/7417d808-44df-11e6-8cda-32afd55ad48c.png)

**Comment by jmfee-usgs** [comment]
It's a little strange to have the navigation link "Tell Us!", but modal dialog title "Felt Report".  Not sure how best to incorporate that text.

**Comment by ehunter-usgs** [comment]
In response to Eric,
 - The numbers were intentionally squished because as the numbers grew larger and larger it became harder to read it as a single number. However, on second look i like it the way i originally styled it with more padding (see PR)
 - The gradient does look better when it's a bit more faint (see PR)
 - I like the idea of left-padding for an "odometer" look, maybe we should pick a number of digits and always display that many. I would say 6-digits (that covers Virginia)
 - I would argue to keep the title the same as it is in section navigation (Tell Us!)
 - I agree that the contributor could change. I'm curious as to what Vince or Dave would suggest?

**Comment by ehunter-usgs** [comment]
I went with this:
<img width="231" alt="screen shot 2016-07-08 at 1 55 27 pm" src="https://cloud.githubusercontent.com/assets/1932750/16699827/b516fc1a-4513-11e6-9416-1bcd6c1f1a9d.png">

**Comment by jmfee-usgs** [comment]
- left pad should probably be a utility method
- change contributor/footer

**Comment by jmfee-usgs** [comment]
Unused variable:
- https://github.com/usgs/earthquake-eventpages/pull/621/files#diff-2afde9cab62e9969befdf932c25b4f21R56

"Contributed by X" vs "X Contributions" seems out of place.
