### ISSUE TITLE
DYFI Questionnaire no longer sending event ID?

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/earthquake-eventpages#580]
I tried sending a questionnaire via the "Tell Us?" link on the event page:

http://earthquake.usgs.gov/earthquakes/eventpage/uw61176166#dyfi

The output no longer sends the event ID. This means the backend has trouble associating this entry with the correct event. Please fix.

**Comment by emartinez-usgs** [comment]
@vinceq-usgs : What specifically does the backend expect as a parameter? "eventid=uw61176166" or "id=uw61176166" or ... ? We can fix this but I want to make sure we do it right.

**Comment by vinceq-usgs** [comment]
I just checked the backend code. It used to be 'id'.

**Comment by vinceq-usgs** [comment]
I take it back. The backend is looking for 'eventsourcecode'. But I can change it to whatever is consistent with your naming convention. (I would suggest 'eventid')

**Comment by emartinez-usgs** [comment]
If this is open to change, then for clarity (in-keeping with ComCat conventions), I would suggest "eventsource" and "eventsourcecode" as two separate parameters. When combined, these make up the "eventid". For example:

eventsource = "us";
eventsourcecode = "10004u1y";
eventid = "us10004u1y";

We typically keep eventsource and eventsourcecode separate and only reference "eventid" as a legacy compatibility for understanding.

**Comment by vinceq-usgs** [comment]
In that case let's use "eventid" then.
