### ISSUE TITLE
Update styles to be more consistent

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#638]
Make the pins look more uniform:
 - no serifed headers
 - impact bubbles should all look the same
 - top-margin on similar content patterns

**Comment by ehunter-usgs** [comment]
not sure why this isn't being linked:
https://github.com/usgs/earthquake-eventpages/pull/637

**Comment by emartinez-usgs** [comment]
the "fixes" statement needs to be in the pull request title or description. putting a "fixes" statement in a comment will have no effect.

**Comment by ehunter-usgs** [comment]
ahhh i see thanks @emartinez-usgs
