### ISSUE TITLE
DYFI header

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-eventpages#639]
add 'Felt Report - Tell Us!' under 'Did You Feel It?'

**Comment by emartinez-usgs** [comment]
Also change the header on the form that opens to be "Felt Report - Tell Us!"

**Comment by ehunter-usgs** [comment]
I added that to issue-640 so jdbrown-usgs should be handling that with his changes

**Comment by ehunter-usgs** [comment]
This is changed in the module title, that is the only place it should need to be changed.
