### ISSUE TITLE
fe region number blank or ndash

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-eventpages#642]
Blank or null values are seen as ndash.
Should we fall back to other numbers or leave blank/ndash.

example event
us200066x9

**Comment by jmfee-usgs** [comment]
I'll talk to Bruce

**Comment by ehunter-usgs** [comment]
I think it's ridiculous that we report the number at all, so i'm okay with this

**Comment by ehunter-usgs** [comment]
Update the logic to choose the first name and first number
