### ISSUE TITLE
Remove fe number

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-eventpages#652]

**Comment by ehunter-usgs** [comment]
Strip out all the extra logic to make sure a number and name are defined. Just use the first name.

**Comment by jmfee-usgs** [comment]
Should we even include _any_ FE information?  We already have a location name in the title.

**Comment by jdbrown-USGS** [comment]
Removed fe information from Regional Information.

**Comment by jdbrown-USGS** [comment]
removed FE information from regional information
