### ISSUE TITLE
impact bubbles in FireFox

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#654]
Floats are fun in FireFox, update to use flex layout.

**Comment by ehunter-usgs** [comment]
![screen shot 2016-07-13 at 10 50 43 am](https://cloud.githubusercontent.com/assets/1932750/16812403/2a7c192a-48ea-11e6-9b4b-a38c84df90cd.png)

**Comment by jmfee-usgs** [comment]
Seems strange to set this here _and_ in pager pin view css:
https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/css/core/_BasicPinView.scss#L31

https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/css/losspager/_PAGERPinView.scss#L20
