### ISSUE TITLE
Felt Report - Tell Us! ios bug

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-eventpages#659]
- Once a form is submitted the form scrolls back to the top with no indication that it was actually submitted. If you scroll back down you will see that another felt report from is below the original and this continues for each time the submit button it hit. this only seems to be happening on IOS devices.

**Comment by ehunter-usgs** [comment]
It's unclear whether or not it's actually submitting. Do we contact Vince to verify this for events on development?
