### ISSUE TITLE
Make DYFI Intensity vs. Distance Plot distances round numbers

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/earthquake-eventpages#664]
![screen shot 2016-09-23 at 5 24 41 pm](https://cloud.githubusercontent.com/assets/16106146/18804653/b832ecfc-81b2-11e6-9073-f789d2eebd00.png)

Make the distance labels round numbers (60, 600) instead of (66.003,605.764)

**Comment by ehunter-usgs** [comment]
Verify using:
https://earthquake.usgs.gov/earthquakes/eventpage/nc72832766#dyfi
