### ISSUE TITLE
Nearest places have populations of 0 or -

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-eventpages#666]
See, for example:

http://earthquake.usgs.gov/earthquakes/eventpage/nc72728005#region-info
http://earthquake.usgs.gov/earthquakes/eventpage/ci37746480#region-info

**Comment by jmfee-usgs** [comment]
The event pages appear to be working as expected.  See the nearby-cities JSON files contributed by NC and CI networks.

The NC file sets population to 1:
http://earthquake.usgs.gov/archive/product/nearby-cities/nc72728005/nc/1479770061207/nearby-cities.json

The CI file sets population to null:
http://earthquake.usgs.gov/archive/product/nearby-cities/ci37746480/ci/1479755715887/nearby-cities.json

I will forward this issue to those contributors to comment.  If you'd like these values handled differently, please reopen and comment on how the event pages should be changed.
