### ISSUE TITLE
DYFI form - multiple checkboxes only sending last value

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/earthquake-eventpages#680]
The DYFI Questionnaire form "d_text" field isn't properly handled by PHP so the $_POST variable is only sending the last value checked. PHP needs the field to be "d_text[]" instead.

https://github.com/usgs/earthquake-eventpages/blob/master/src/htdocs/js/languages/en.json#L171

**Comment by ehunter-usgs** [comment]
replaced by: https://github.com/usgs/earthquake-dyfi-response/pull/9

**Comment by ehunter-usgs** [comment]
should be merged and deployed with: https://github.com/usgs/earthquake-dyfi-response/pull/9
