### ISSUE TITLE
Update DYFI Pin Image

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#695]
@vinceq-usgs would like to see the image on the DYFI pin updated to use the geocoded map.

**Comment by vinceq-usgs** [comment]
Can we have this pin image be a small thumbnail version of the interactive map with 10km geocoded boxes? (instead of jpg)

**Comment by llastowka-usgs** [comment]
What does this do to event page performance? What if other products want dynamic data plotted? Is there some tipping point we need to be aware of?

**Comment by vinceq-usgs** [comment]
I too am interested in the answer. We'd like to eventually replace all of the DYFI static image products with Leaflet-driven maps.

**Comment by jmfee-usgs** [comment]
@llastowka-usgs : that's a good question.

@vinceq-usgs : can you provide details on the JSON size for a large event like Virginia?

Leaflet based maps seem like the way to go for DYFI specific pages, but not sure at the summary level where users haven't yet selected more detailed information; we want to minimize bandwidth usage for the initial page view, especially for mobile users who frequently have limited data.

We show the ShakeMap contours by default across various interfaces (event page executive summary and interactive map, kml event details, etc).  We have not yet included DYFI? by default, and I'm concerned that this will be a significant overhead for significant events.  Maybe DYFI should produce contours, or maybe stick with a small thumbnail image.

**Comment by vinceq-usgs** [comment]
@jmfee-usgs good question, the 10km-geocoded GeoJSON file for Virginia is 900Kb and the 1km file is 3Mb. I expect that for most cases, it's the 10km file that we want. That's 3,761 polygons to be rendered (less, because some of those will be outside the map boundary.)

**Comment by vinceq-usgs** [comment]
Another thought, once we get out of static image creation for DYFI, I can create a special super-small thumbnail GeoJSON that only has data in a small area. For example, a zoom-in version 100km on a side will have 100 10km blocks maximum.

**Comment by jmfee-usgs** [comment]
The current "thumbnail" (not really a thumbnail, we scale the full size image down) is 500KB.  My target is ~10KB for a DYFI thumbnail or summary data.

The event pages currently check for an image named `pin-thumbnail.png` at the root of the DYFI product, if you can produce a smaller thumbnail before the GeoJSON is ready...

**Comment by vinceq-usgs** [comment]
How about a `pin-thumbnail.geojson?`

**Comment by ehunter-usgs** [comment]
@vinceq-usgs I like the pin-thumbnail.geojson idea. Would it be hard to create one for the Virigina event so that we could compare the file size?

**Comment by ehunter-usgs** [comment]
Added issue to reflect the comments above. Feel free to add any additional comments in the new ticket!
https://github.com/usgs/earthquake-eventpages/issues/710
