### ISSUE TITLE
Update DYFIPinView to use Leaflet Map

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#710]
_This issue has been created as a result of discussion on https://github.com/usgs/earthquake-eventpages/issues/695_

This requires more discussion, but Vince would like to see the DYFI pin utilize the DYFI Geospatial Data with 10km spacing(dyfi_geo_10km.geojson) that is displayed on the interactive map.

Concerns:
 - For large events this would require the user to download large files without explicitly requesting them (3mb for virginia)

Solutions:
 - Vince could create a thumbnail.geojson file at a 100km spacing that may significantly reduce the size. 

It would be worth working with Vince to see how feasible this is since we are already loading leaflet to display the interactive and regional pins.

**Comment by jmfee-usgs** [comment]
@vinceq-usgs : can you comment on file size for Virginia using 100km spacing?  Do you have other ideas about how to summarize DYFI on the pin view that have low bandwidth impact?

**Comment by vinceq-usgs** [comment]
Right now the dyfi_geo_10km.geojson file is 900kb. 100km blocks would look way too big, I'd imagine. 

I can create a new 10km geojson specifically for thumbnails. I got Virginia down to 373kb by:

(1) setting a ~1000km rectangle around the epicenter, then removing all blocks outside. If you give give me a smaller bounds (or show me the algorithm for determining the bounds of the thumbnail) I can do that automatically.

(2) remove extraneous properties, keeping only cdi and nresp

I haven't tried it, but I should be able to shave off even more bytes if I lower the coordinate precision. Right now I'm keeping 5 decimal places which is way over what a thumbnail needs. What is a reasonable filesize for the thumbnail data?

**Comment by llastowka-usgs** [comment]
planning to simplify DYFI pin to avoid to many maps.

**Comment by llastowka-usgs** [comment]
we will close this and open a new issue for the pin
