### ISSUE TITLE
never prefer a focal mechanism

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#712]
This logic has existed in the past, however was likely lost during refactors.  A couple possible changes:

- do not show preferred checkmark on summary page for focal-mechanism products.
- do not show preferred checkmark on details page for focal-mechanism products.

> Hi Lynda, Paul,
> 
> I just looked at this evening's event, https://earthquake.usgs.gov/earthquakes/eventpage/nc72832766#executive.
> 
> As occasionally happens, there are 2 fault plane solutions provided by fpfit. It is the NC policy (and the CI policy also, as far as I know), that none of the fpfit fault plane solutions is ever preferred. On the Comcast page for this event, this solution is marked as preferred: https://earthquake.usgs.gov/earthquakes/eventpage/nc72832766#focal-mechanism?source=nc&code=nc72832766_fm2
> This is random - it is the second solution provided. It is not preferred! We did not provide information through PDL that it is preferred. Please do NOT mark any of the fpfit solutions that we provide as preferred.
> 
> Thanks,
> Peggy

**Comment by SCEDC** [comment]
I would also suggest something similar on the Overview page -- maybe showing a portion of the table of solutions (with thumbnail of beachballs) without checkmark.

**Comment by ehunter-usgs** [comment]
This will need to be reopened to address the same issue on the summary table.

**Comment by ehunter-usgs** [comment]
Needs to be addressed in #818
