### ISSUE TITLE
Update NearbySeismicityPinView footer

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#718]
Currently it says, "Contributed by NULL". I am not sure what it should say, but perhaps something like, "Contributed by Multiple Networks".

**Comment by ehunter-usgs** [comment]
![screen shot 2017-07-20 at 4 18 42 pm](https://user-images.githubusercontent.com/1932750/28441410-d38a91a2-6d67-11e7-83c8-19d00455c3b7.png)

**Comment by jmfee-usgs** [comment]
This has been fixed in https://github.com/usgs/earthquake-eventpages/releases/tag/v0.8.0
