### ISSUE TITLE
add alt attributes to images

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-eventpages#722]
- nearby seismicity pin
- pager alert histograms

images require alt attribute, can be set to empty if they are only decoration. (nearby seismicity already has headers)

<img src="/archive/product/losspager/us10004u1y/us/1495214189246/alertecon_smaller.png">
<img src="/archive/product/losspager/us10004u1y/us/1495214189246/alertfatal_smaller.png">
<img class="pin-icon" src="images/nearby-seismicity/time.png">
<img class="pin-icon" src="images/nearby-seismicity/radius.png">
<img class="pin-icon" src="images/nearby-seismicity/magnitude.png">

**Comment by ehunter-usgs** [comment]
This ticket has been updated, you should be checking the entire app for alt image attributes.

**Comment by cswilson-usgs** [comment]
All images have alt attributes, so I think this ticket got updated some time ago.....

**Comment by ehunter-usgs** [comment]
I agree, looks good.
