### ISSUE TITLE
Updates/corrections to DYFI Privacy Statement modal pop-up

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-eventpages#725]
This is required in order to submit the renewal for the DYFI OMB permit. The current permit expires 5/31/2018, and it takes about 9-12 months for it to go through the process. I submitted the renewal docs, and they were sent back with this correction request in order for them to go up to the next level for approval.

Required changes are shown on the attached PDF.
[PrivacyStatmentUpdates.pdf](https://github.com/usgs/earthquake-eventpages/files/1265293/PrivacyStatmentUpdates.pdf)

**Comment by lisa-usgs** [comment]
https://github.com/usgs/earthquake-eventpages/pull/726

**Comment by jmfee-usgs** [comment]
Deployed in https://github.com/usgs/earthquake-eventpages/releases/tag/v0.8.3
