### ISSUE TITLE
Impact text and impact links not shown unless dyfi/shakemap/pager product exists

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#737]
For historic events, @paulearle would like to add impact-text type products (these have been sent already), but the ImpactSummaryModule is only shown when `dyfi`, `shakemap`, and `losspager` type products exist.

- Add `impact-link` and `impact-text` to `TYPES` array
- Make sure module layout is okay with only text and/or links

**Comment by emartinez-usgs** [comment]
Navigation does appear with only impact-link or impact-text product types in new angular interface. Layout seems fine (though somewhat lacking in content).
