### ISSUE TITLE
Create angular module for hazdev-template

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#740]
Basic implementation can be found in usgs/earthquake-geoserve-ui project. Use this as a starting point to create a re-usable template module.

**Comment by ehunter-usgs** [comment]
https://github.com/usgs/earthquake-geoserve-ui/pull/91

**Comment by ehunter-usgs** [comment]
Not sure how we want to manage this new hazdev-template branch:
https://github.com/ehunter-usgs/hazdev-template/tree/angular-master

I currently have the app installed on npm under the "beta" tag (see project README):
`npm install hazdev-template@beta` 

I was unable to update the navigation-item component to accept a routerLink input without setting up a router for the hazdev-template (which i think we want to avoid). Any ideas on how to implement that part?

**Comment by ehunter-usgs** [comment]
Here is an example of how to configure earthquake-eventpages to work with the new template:
https://github.com/usgs/earthquake-eventpages/compare/master...ehunter-usgs:hazdev-angular-template

**Comment by ehunter-usgs** [comment]
I updated the hazdev-template project on npm, we are at 2.1.0 now

**Comment by emartinez-usgs** [comment]
Using hazdev-template@2.1.5 ... looks good.

We might need another minor revision after finishing more event page implementation so we can refine some styles to suite our preferences. For now, this is great.
