### ISSUE TITLE
Create angular module geoserve components

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#741]
This will be done in the usgs/earthquake-geoserve-ui project. Make the components re-usable by external projects by converting to module(s).

**Comment by jmfee-usgs** [comment]
This may not require too much.  @dslosky-usgs  put together a quick example of this, it sounds like the geoserve app.module could export the geoserve components without creating a sub module and we could pull this into the event pages as a npm dependency:

- the app module (geoserve) exporting components so they can be re imported
https://github.com/dslosky-usgs/angular-embedding-example/blob/master/src/app/shakemap-app/app.module.ts

- the app module (event pages) importing from the another "app module"
https://github.com/dslosky-usgs/angular-embedding-example/blob/master/src/app/app.module.ts

Once earthquake-geoserve-ui is published to npm, we'd just use a node_modules relative url to import, i.e. 'earthquake-geoserve-ui/src/app/app.module'

**Comment by ehunter-usgs** [comment]
@jmfee-usgs he is exporting the ShakemapComponent, but he is still importing the whole ShakemapModule in his app. This is what we are doing with earthquake-geoserve-ui, we have a hazdev-template.module that exports the hazdev-template.component, then we package the project with npm and import the hazdev-template.module and use the hazdev-template.component

**Comment by ehunter-usgs** [comment]
I am fixing tests, but here is my solution:
https://github.com/usgs/earthquake-geoserve-ui/pull/92

Also the geoserve components can be included in the project by `npm install earthquake-geoserve-ui`

**Comment by emartinez-usgs** [comment]
To use ... `npm install earthquake-geoserve-ui`, then import `GeoserveOutputModule` into app module for components, and then `import { CoreModule as GeoserveCoreModule } from ...` and `GeoserveCoreModule.forRoot()` in app module to use services.

**Comment by dslosky-usgs** [comment]
This looks great @ehunter-usgs, I'm going to copy what you've done for the event pages.

It might make more sense to change the name of geoserve's core module on export, rather than import.

in the public_api.ts:
`
import { CoreModule } from './src/app/core/core.module';
export let GeoserveCoreModule = CoreModule;
`

**Comment by ehunter-usgs** [comment]
https://github.com/usgs/earthquake-geoserve-ui/pull/92
