### ISSUE TITLE
Implement angular router for different event page modules

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#743]
For example:
  ` .../eventpages/#eventid/shakemap` Should display the ShakeMap module.

There may be other sub-parameters to a module in order to support custom actions/views to be rendered by default on the module pages.

Scaffold out other product modules to verify router works as expected.

**Comment by jmfee-usgs** [comment]
I believe this is already implemented, for other modules see #750

**Comment by emartinez-usgs** [comment]
Still needs to scaffold out...
- ImpactSummaryModule
- TechnicalSummaryModule

Though this should be pretty basic.

**Comment by jmfee-usgs** [comment]
- Getting test errors "app-dyfi-summary" is not defined.

- Update names for component element selectors:
  - Impact component should be `impact`
  - DyfiSummary component should be `impact-dyfi-summary`
  - Technical component should be `technical`
  - etc...

**Comment by jdbrown-USGS** [comment]
-Fixed tests
-Updated names
