### ISSUE TITLE
Implement Navigation Module

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#746]
Create a module for displaying navigation for all available product modules.

**Comment by jmfee-usgs** [comment]
- needs tests

- templateSideNavigation attribute seems redundant:
  - don't need https://github.com/usgs/earthquake-eventpages/blob/master/src/app/event-page/navigation/navigation.component.html#L3
  - already have https://github.com/usgs/earthquake-eventpages/blob/master/src/app/event-page/event-page/event-page.component.html#L6

- remove console logging

**Comment by emartinez-usgs** [comment]
Regarding the last point, I think we decided "Scientific" steered people away from the content, as if to say, "this is for scientists only". Technical (we thought at the time) was more inviting to all backgrounds.

I don't care what we call it, and in general I'm a fan of consistency. I would say "technical" and "Technical" across the board. This initial work is simply mirroring how the previous project was set up.
