### ISSUE TITLE
Implement Impact Summary Module

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#748]
This module should render the following content (in order):

- impact-header products
- summaries for each available impact product
- impact-text products
- impact-link products

When in doubt, defer to how current event pages have implemented this logic.

**Comment by jmfee-usgs** [comment]
see #778 for `shared-text-product` component example (for rendering impact-text)

**Comment by jmfee-usgs** [comment]
Better test coverage is needed.
