### ISSUE TITLE
Origin module scaffolding

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#750]
Create an origin module. It should render a tabbed interface similar to the exiting origin module implementation. Each tab should defer content rendering to a sub-component within the module. The scaffold should simply output sub-component identifier. Implementing sub-components left as separate issues.

**Comment by emartinez-usgs** [comment]
I get the following error trying to run the code, while the error makes sense, it's not immediately obvious to me how to fix it...
```
core.js:1440 ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
```

**Comment by jmfee-usgs** [comment]
Definitely not obvious, but related to the BrowserAnimationsModule.  Also strange that this was working when the PR went in, maybe the package.json changes earlier today that I rebased against without retesting...

I moved that import to AppModule from ProductPageModule and it seems to work again.
