### ISSUE TITLE
Origin Module Magnitudes

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#753]
Implement content to render within the "Magnitudes" tab of the origin module. See existing event page implementation for details.

**Comment by jmfee-usgs** [comment]
depends on #750 , coordinate quakeml parsing with #752

**Comment by emartinez-usgs** [comment]
**Visual**
- Tab content does not appear to be "in" the tab. Padding/margin can help with this.
- Individual magnitudes not well delineated.
- Why the new layout?
- Expansion panels need more clear call to action. Blue "Details" link previously.
- It is not immediately clear why some expansion panels are disabled (eg. when station data not available).
- Station data does not render well on small screens.
- Downloads dialog indicates "Download Station Magnitudes", maybe "Download Station Data" is more appropriate since magnitude is just one part of the data.
- Maybe buttons could use the `mat-button` or similar attributes?

**Implementation**
- Coding standards. Space between function name and opening parens in declaration.
- Probably still use `===` even when comparing to `null`.
- Magnitude source should fall back to product source ?
- Use `&nbsp;` when parsing amplitude/units
- When falling back to `&ndash;` should check if numeric value  === 0 before falling back
- Has `stationMagnitude` data structure changed? Previously we checked `status`, but now checking `evaluationMode`.
- The `routerLinkActive` seems buggy.
