### ISSUE TITLE
Implement Origin Pin

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#756]
As component of Origin Module

**Comment by jmfee-usgs** [comment]
@ehunter-usgs : this should be part of the executive module, not the origin module

**Comment by emartinez-usgs** [comment]
- Change `app-origin-pin` selector to simply `origin-pin`.
- Be sure to capture `null` case for product properties and use `&ndash;` appropriately.
  - Review Status
  - Magnitude (and Type)
  - Time
- Prefer `formatterService.dateTime` over built-in `date` pipe
- Probably use `formatterService` for other outputs (which captures `null` values already)
- Maybe abstract out some of the common implementation (structure, styles, etc...) to a generic pin component ? Maybe this can be done as part of the next pin.
- Need tests for `ngOnChanges` method
- Thoughts on an "attribution" component rather than a repeated design pattern?

**Comment by emartinez-usgs** [comment]
- Should call `date` and `time` methods separately with `<br/>` in between.
- Prefer: `date: number|string|Date`
- Maybe simply `if (!(date instanceof Date)) { ... `
- Documentation: `stamp` is not a parameter for the `date` method. `{value}` should indicate acceptable data types.
- `magnitude` method should check for `value === 0` and not use `this.empty`
- Empty strings evaluate to false, so `!status || status === ''` is redundant

- With more thought, I think `origin-pin` selector should actually be `executive-origin-pin`. My bad.
