### ISSUE TITLE
Implement Regional Information Pin

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#757]
As component of Regional Information Module

**Comment by emartinez-usgs** [comment]
**Implementation**
- Change class name to `region-info-pin`
- Change selector to `region-info-pin`
- Remove `console.log` statements
- Use sub-domains on tileLayer URL.
- Coding standards
  - Use a space between function name and opening parens during function declaration/definition
  - Prefer `L.marker` over `new L.Marker` (unless this doesn't work)
- Why was 'earthquake.usgs.gov' added back to environment config? Is this not fixed with `npm start` ?
- Probably should abstract out the pin view now that there are two we can see commonalities and room for code re-use.
  - Headers strucuture / styles
  - Attribution structure / styles
  - Call to action structure / styles
- Unit tests need more coverage (currently 66/35/85/64).

**Visuals**
- Pins should be same height/width
- Map should have left/right margin and be centered in pin container
- Pin highlighting ...
- I kind of like the attribution on bottom with the beveled (?) separator

**Comment by ehunter-usgs** [comment]
Using a basic pin view feels more complicated to me. I would rather just create a component for things like the attribution section of the pin and reuse those across the different pin views. This is my abstraction of a basic pin view and implementing the `regional-info` and `origin` pins:
https://github.com/usgs/earthquake-eventpages/commit/b0fcd89728eadf80e322e6b1a18b4dcee55ace39
