### ISSUE TITLE
Enable codacy

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#764]

**Comment by emartinez-usgs** [comment]
https://app.codacy.com/app/usgs/earthquake-eventpages/dashboard

Note: Codacy is checking pull requests...
https://github.com/usgs/earthquake-eventpages/pull/766

Travis is uploading coverage reports to codacy...
https://app.codacy.com/app/usgs/earthquake-eventpages/files?bid=6543348&filters=W3siaWQiOiJjb2x1bW5JbmRleCIsInZhbHVlcyI6WzVdfSx7ImlkIjoic29ydE9yZGVyIiwidmFsdWVzIjpbIkRlc2NlbmRpbmciXX0seyJpZCI6InNlYXJjaFRleHQiLCJ2YWx1ZXMiOltudWxsXX1d
