### ISSUE TITLE
ShakeMapModule

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#805]
- Create basic module scaffold
- Create stationlist component
- Create metadata component

Map component will be done later.

**Comment by jdbrown-USGS** [comment]
- input.component.html, output.component, processing.component.html, and input.component.html all have ngIf checks for a dt and dd element. Only one check is needed here then populate the dt and dd. 

- Station.component.html,  MMI is wrapped in a h1 tag causing font to be larger than needed.
