### ISSUE TITLE
Compatibility with older versions of ShakeMap

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#826]
Some products (even info.json) may be missing

stationlist.json has some numeric values occasionally set to string values: 'null' or 'nan' which break rendering

**Comment by emartinez-usgs** [comment]
- index.ts should have a trailing newline character
- While #835 seems to suppress console errors, it does not address actually rendering what content _is_ available. Given the slow adoption for ShakeMap contributors to update their software, I think we need ShakeMap to render what content is available regardless of format.

**Comment by dslosky-usgs** [comment]
Should we go so far as to translate the old info.xml into info.json?

**Comment by jmfee-usgs** [comment]
Yes, if the ShakeMap group would like metadata displayed for old events.

**Comment by dslosky-usgs** [comment]
Did the old pages actually parse old shakemap's info.xml? It looks like there might not have been an alternative if the info.json was missing:

https://github.com/usgs/earthquake-eventpages/blob/c5fcae654cfaed6613fc7a9fda8592a6d1433d86/src/htdocs/js/shakemap/ShakeMapView.js#L132

**Comment by dslosky-usgs** [comment]
We're parsing stationlist.xml and info.xml files are nowhere to be found (thanks @kmarano-usgs for looking)... I think we can call this one closed until we actually encounter an issue
