### ISSUE TITLE
Add "load more" functionality to station list

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#836]
Rendering tons of stations slows down the UI; only load 100 at a time

**Comment by jmfee-usgs** [comment]
This is likely related to how the shared-station component is using the getAmp function in the template, which may be called repeatedly during change detection.

A more performant option is the use an input property setter to parse the station once, and display only parsed data:

```
@Input() set station (station: any) {
  // parse the station amplitudes
}
```

Another, possibly better, alternative would be to parse the station list into a standard format in the station service.

**Comment by dslosky-usgs** [comment]
Redirected to #840
