### ISSUE TITLE
OAF Pin

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#838]
Create pin for operational aftershock forecasts. This is static content (for now). Attribution should honor product source. Future enhancements may become product-specific.

See attached image for mockup of desired design. A blue background (instead of grey) would also be acceptable.

![screen shot 2018-03-22 at 12 28 13 pm](https://user-images.githubusercontent.com/1726751/37790635-bb486e40-2dcc-11e8-86a1-984fa88172d4.png)

**Comment by emartinez-usgs** [comment]
@michael-usgs @jmjones-usgs @llastowka-usgs 

Let's continue future pin design/discussions here rather than email.  Please tag Sara or others as appropriate.

**Comment by llastowka-usgs** [comment]
I think just the text in the box would be a better option. I don't think the lines above add much. people will click on it either way to get  the real info so I would suggest to keep it short.

**Comment by michael-usgs** [comment]
My reason for wanting the explanation is that people may not know anything about aftershock forecasts and what they might consist of.

**Comment by McBeeFabulous** [comment]
Hi, I found the team! I can see arguments for both but, given that aftershock forecasts are quite new to most people, I think a brief sentence explaining what it is would be a good idea.

**Comment by jeanneha** [comment]
Hi!  I'd also prefer keeping a brief explanation of what the forecast is.

**Comment by michael-usgs** [comment]
Sara, Jeanne, and I have a new suggestion for the explanatory text:
Learn about our model for expected numbers and odds for future earthquakes.

Thoughts?

**Comment by llastowka-usgs** [comment]
I think that is good, but we should not personalize it with "our".   A model? The model?  A scientific model? just "Learn about expected numbers..."? @lisa-usgs may have a suggestion!

**Comment by McBeeFabulous** [comment]
We use "our" in the template, to personalize the information and to warm the tone of our work.  Providing personal tone is important in that this creates a sense of ownership for the model and that people run the model.  It is unusual in scientific writing to use personal pronouns but not in websites or blog posts, which are fundamentally quite different and serve different purposes.  Shifting to a more personal voice is important if we want people to engage in our topics. 

We could say USGS model, if you are really opposed to "our".

**Comment by McBeeFabulous** [comment]
Here is an excerpt for our website: 

"We provide science about the natural hazards that threaten lives and livelihoods; the water, energy, minerals, and other natural resources we rely on; the health of our ecosystems and environment; and the impacts of climate and land-use change. Our scientists develop new methods and tools to supply timely, relevant, and useful information about the Earth and its processes."

Our and we are used liberally already on our website.

**Comment by jmfee-usgs** [comment]
I recommend keeping the pin content _very_ brief and simple.  "Aftershock Advisory" or "Aftershock Forecast", and ideally something specific to this event.

Users are scanning a lot of information in this context, and may skip over text.  On the details page, a user is looking for more information and is (hopefully) willing to read more carefully.

**Comment by llastowka-usgs** [comment]
That introductory paragraph is from a different part of the website  The event pages are their own application/set of information and need to be internally consistent in tone and style, especially at the summary level.   We don't say our shakemap, our origins, etc.  If you look at all the other pins you can see no others have text even though the content is complex.

**Comment by michael-usgs** [comment]
We will eventually have event specific information in this spot.  The text we are discussing now is basically a placeholder until we develop the pin product.  Doing so, allows us to have implement the main product and have a pin in the meantime.

Given the novelty of the aftershock forecast outside of California, we feel that some explanatory text of what is inside will be useful.  Eventually the event specific information will be an example of the content and thus will implicitly convey a similar idea.

I hope we can experiment a bit with tone and presentation.  We got Sara to join our group so we could have the benefit of her extensive experience in hazards communication and social science research.

**Comment by michael-usgs** [comment]
Note: DYFI says, "Tell Us"  in two places and not "Tell the USGS"
