### ISSUE TITLE
Interactive Map Pass 2

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#849]
layer chooser, show layer control parameter
legend control, show legend control parameter
global interactive input parameters, default to true
(if it is non interactive hide controls, optional scale and attribution)
fix attribution control, show attribution control parameter
fix scale, show scale control parameter
expose leaflet map object
specify default base map as input parameter
specify overlays as input parameters
add epicenter to map
use +/-  2 degrees for extent

**Comment by llastowka-usgs** [comment]
layer chooser, show layer control parameter
legend control, show legend control parameter
global interactive input parameters, default to true
(if it is non interactive hide controls, optional scale and attribution)
fix attribution control, show attribution control parameter
fix scale, show scale control parameter
expose leaflet map object
specify default base map as input parameter
specify overlays as input parameters

**Comment by ehunter-usgs** [comment]
This ticket will be used to evaluate progress at review time

**Comment by llastowka-usgs** [comment]
these are all accounted for.
