### ISSUE TITLE
Loading Screen 

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#860]

**Comment by llastowka-usgs** [comment]
Improve loading experience

**Comment by ehunter-usgs** [comment]
With the fallbacks we have on product pages, when the product information has not yet loaded the page says, "Failed to load". A loading screen would be nice.

**Comment by llastowka-usgs** [comment]
I am taking this out of this milestone 1.13, we can come back to this.

**Comment by llastowka-usgs** [comment]
we have a loading screen in 1.17
