### ISSUE TITLE
Add interactive parameter to shared-map

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#863]
When false
- suppress pointer events
- suppress other interactivity
- suppress interactive controls
  - zoom
  - layer chooser

**Comment by ehunter-usgs** [comment]
There are examples of non-interactivity in the region info pin

**Comment by emartinez-usgs** [comment]
- Pointer events none should be added to the shared map itself, and only when the map is not interactive
  - Remove other references
- Interactive property should be private with public getter/setter methods. The setter should call a new method `updateInteractive` and `updateControls` once the value is set.
  - The new `updateInteractive` should be called after map is initialized. Do not set interactive values during `ngAfterViewInit`.
  - The new `updateInteractive` method should enable/disable each interactive aspect of the map (zooming, animations, etc...) based on the current value for `this.interactive`.

Currently once a map is initialized as either interactive or not, it can not be changed. The above steps _should_ remedy this.
