### ISSUE TITLE
Add shared-map showLegendControl parameter

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#865]
When set to true (use an input set method) add legend control to map.
When set to false, remove legend control from map.

**Comment by llastowka-usgs** [comment]
Update the update controls method

**Comment by ehunter-usgs** [comment]
I didn't touch any of the code organization. Are we waiting to refactor stuff inside "shared"?

**Comment by jmfee-usgs** [comment]
- recommend creating a stub legend control, could say "legend works" for now
- add test coverage for changes
