### ISSUE TITLE
Implement legend control

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#866]
- possibly reference layers control to see which layers are on map?  possibly reference overlays input to see which layers are on map?

**Comment by jmfee-usgs** [comment]
It sounds like @dslosky-usgs may have an implementation that can be integrated next sprint

**Comment by llastowka-usgs** [comment]
Get information from overlays using shared map stuff

**Comment by dslosky-usgs** [comment]
I see you assigned to this @jdbrown-USGS; should I still be working on this as well?

**Comment by jmfee-usgs** [comment]
Feedback flowing over from #865's skeleton:

- Leaflet controls seem to vary in size based on .leaflet-touch, I think we should mirror those styles for consistency:

https://github.com/Leaflet/Leaflet/blob/2ce37c5771589aebbb39fb133d7d456bc9b649a1/dist/leaflet.css#L345
https://github.com/Leaflet/Leaflet/blob/2ce37c5771589aebbb39fb133d7d456bc9b649a1/dist/leaflet.css#L354

- clean up event handlers
- move `leaflet-control` mixin into leaflet-styles.scss

**Comment by jmfee-usgs** [comment]
@jdbrown-USGS : rebase against this pull request, https://github.com/usgs/earthquake-eventpages/pull/907 , which manages the `enabled` property for Overlays.  There is a comment on line 235 of shared/map/map.component that you could replace with something like `this.legendControl.update(this.overlays)`...
