### ISSUE TITLE
Station update

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#890]
- Remove the mat-card wrapper
  - use a header with station name/code (similar to existing pages)
  - use shared-bubble components for the summary information (see origin/magnitudes component)
  - combine station latitude/longitude into location (similar to existing pages)

- Display channel/amplitude flags, for example event ci37904927 station FRD
  - https://github.com/usgs/earthquake-eventpages/blob/master-pre-angular/src/htdocs/js/shakemap/ShakeMapStationListView.js#L10

**Comment by jmfee-usgs** [comment]
Use `abbr` tags for channel details headers, for example:

```
<abbr title="Peak Ground Acceleration">PGA</abbr>
```

**Comment by dslosky-usgs** [comment]
@jmfee-usgs should we update the look of the channel/amplitude flag?

Current:
![Screen Shot 2018-04-09 at 3.45.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57068a3bb508520e00b309bd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454fa6b7191a37bf1162e4f5f5d5ecc3c4a4356bcbbd671f3e57862804e0ee984690c72c43819adecd049b600ee208b48d4e5ee824ad2f42f67b6d5db1063474f4dcbed5727a29b41c95df448e24c55a716326be7732431.png)

Or we can make outliers more obvious:
![Screen Shot 2018-04-09 at 3.45.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57068a3bb508520e00b309bd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454fa6b7191a37bf1162e4f5e565ecc3c4a4356bcbbd671f3e57862804e0ee984690c72c43819adecd049b600ee208b48d4e5ee824ad2f42f67b6d5db1063474f4dcbed5727a19141c95df448e24c55a71b3360e7742431.png)
