### ISSUE TITLE
Jenkins Build

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-eventpages#891]
Currently, if a step/stage fails the build without throwing an exception (eg. DependencyCheckAnalyzer), then an email is not sent notifying admin of the problem. This should be corrected so emails are sent whenever the build fails.

For example:
- In catch block, simply set FAILURE = e
- After cleanup, create an "email" stage
- In email stage, check `currentBuild.result` and `FAILURE` values.  Send email if either indicate failure
  - Some more effort may be required to generate reasonable mail content depending on how/why the build failed.

**Comment by llastowka-usgs** [comment]
I think this happens I get a lot of emails...
