### ISSUE TITLE
Install on Prod

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#895]
Add routing for Beta location, deploy

**Comment by emartinez-usgs** [comment]
Steps to install...
- Added beta path to routing tables on production configuration
- Manually pulled image to container host
- Manually tagged image as local:active
- Ran jenkins "deploy" job against production environment using "1.3.0"

Result:
- Application available for preview on production systems
- Check "metadata.json" to verify version
- Use any event (or helpful link) to verify proper rendering

Note:
- Merged PR results automatically go to staging systems
- All production deploys require manually running jenkins deploy job against production environment
- All production deployments should use a specific tagged version number (not latest)
