### ISSUE TITLE
Template Navigation Scrolling

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#896]
Remove it
Full height of the tallest of the content or navigation
Work on mobile
Publish to NPM

**Comment by jmfee-usgs** [comment]
see https://github.com/usgs/hazdev-template/pull/290

**Comment by emartinez-usgs** [comment]
Page footer renders on top of navigation menu on mobile when navigation is longer than page content.

**Comment by emartinez-usgs** [comment]
Merged. Needs to be published to NPM and integrated with event pages.

**Comment by jmfee-usgs** [comment]
@ehunter-usgs the `npm run package` command generates errors, did you get these last time?

**Comment by ehunter-usgs** [comment]
@jmfee-usgs yes the command does generate warnings, but everything works as expected, so I was just ignoring them.
