### ISSUE TITLE
Occasional test failure

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#910]
These tests are failing occasionally since rebasing this morning. Does anyone know what's going on?

<img width="1193" alt="screen shot 2018-04-11 at 6 45 39 am" src="https://user-images.githubusercontent.com/17622719/38619527-8fc9763c-3d59-11e8-90c1-d67b9d21a809.png">

**Comment by llastowka-usgs** [comment]
this is no longer relevant
