### ISSUE TITLE
Make Ground Failure Module Skeleton

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#914]
Say this page works

**Comment by llastowka-usgs** [comment]
include paragraphs in footer
get rupture warning from product property

**Comment by emartinez-usgs** [comment]
Per @kallstadt-usgs :
 - Several of the links do not have content yet, so they were removed. Easy to add back later.
- "ShakeMap version 3" is worded as "the current ShakeMap" until the version information is added as a the ground-failure product properties
  - Notably, the ShakeMap link always links to the current ShakeMap, even if  the text describes an older version.
- The second part of second paragraph is rendered conditionally on the `rupture-warning` property of the current ground-failure product.
