### ISSUE TITLE
Create Ground Failure about component

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-eventpages#917]
With text for now.

**Comment by emartinez-usgs** [comment]
- Background link should use site-relative link: `/data/grdfailure/background.php`.
- Change phrasing:
  - FROM: "...details about the models and alert levels"
  - TO: "...details about our models and alert levels"
- Move comma outside of quotation marks `"sand volcanos,"` --> `"sand volcanos",`
  - Be sure to use ldquo/rdquo (ansi equivalents) for quotes
