### ISSUE TITLE
Create additional shakemap overlays and tabs

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#942]

**Comment by jmfee-usgs** [comment]
You might add an additional check whether each image exists, and show a message if it doesn't.  It's possible, probably rare, for a user to navigate to a page even if we don't link directly to it.

Should the same legend be shown for PGA/PGV?

Is there a legend for PSA?

You might disable the shared-map attribution for the static images, it will still be shown on the larger map...
