### ISSUE TITLE
Update ground failure pin icons

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#948]
see attached svg

**Comment by jmfee-usgs** [comment]
[ground-failure-svg.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e4ce5b1f3e990c00bab6dd/125516c66e82c728ace21e0d46ef8695368c87e489e8b64fb14ff5d93a5020316546b3397f8fe62bab0021435a5b1ba8125e5d41f4f8dd79f0bf3d248a5c0cbc823f5772d42103eee9dc4be05ce36ade0d97bcae8b4bcae93827e38e8f493d16021c8ff84f78.zip)

**Comment by ehunter-usgs** [comment]
Use the `landslide-alert` property instead of the `landslide-hazard-alert-color` property. 
Use the `liquefaction-alert` property instead of the `liquefaction-hazard-alert-color` property.

**Comment by jmfee-usgs** [comment]
Also change the word "people" to "population", and possibly reduce the spacing around icons...
