### ISSUE TITLE
PagerCitiesComponent

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#963]
Generate a table that looks like the old "selected cities exposed" table. Display the first ten cities and hide the rest with a button to expand the full table.

**Comment by jmfee-usgs** [comment]
please rebase

**Comment by emartinez-usgs** [comment]
A few issues...

- Should render first 11 cities as they appear in pager.xml file when not showing full list
- Probably want a different approach to showing/hiding selected/all cities. Maybe not a CSS approach?
  - `nth-child` does not behave like you might expect. Consider the following selector `.klass:nth-child(n)`. This looks for elements with the class name `klass` and elements that are the `nth` child of their parent, but not necessarily the `nth` child element that _also_ has the class `klass`. Consider:
```html
<!-- CSS -->
<style>
.klass:nth-child(1) {
  font-weight: bold;
}
</style>

<!-- HTML (will not match) -->
<div>
  <p>First Child</p>
  <p class="klass">Second Child</p> <!-- NOT bold -->
</div>

<!-- HTML (will match) -->
<div>
  <p class="klass">First Child</p> <!-- Bold -->
  <p>Second Child</p>
</div>
```
