### ISSUE TITLE
Station Overlay Enhancements

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#985]
Related to #967, #976

The station layer used to be enabled when linking to the interactive map from the shakemap page, and now that an image isn't being sent possibly also enabled on the shakemap page.  Not sure whether it should also be enabled for other tabs like PGA?

I see some weird css behavior when you load the interactive map first, compared to when you load the interactive map after another page with a material table.  Not sure whether the table styles are global?  Maybe importing into the App module would fix that, or maybe we should consider bundling one of the modules in the root level...

I recommend moving all the MMI variables into the shared css file.  Would the text-color/font-family/etc rules interfere elsewhere?

Are the defaultOptions in AsynchronousGeoJSONLayer the same as in leaflet?  Could point to layer just be L.GeoJSON.prototype.pointToLayer (if that's a thing)?

Can the bubble styles be moved into a shared css file, so they don't need to be repeated?

Group imports at the top of files, src/styles.scss, shakemap-stations-overlay.ts,

**Comment by jmfee-usgs** [comment]
@dslosky-usgs : I added the `babel-polyfill` polyfill to the page to load in IE11.  The custom elements in popups do not work in IE11, and appear to also not work in Edge.  Have you found anything related to making these work in other browsers?

@emartinez-usgs : how do you feel about popup content being value added on the interactive map?

**Comment by dslosky-usgs** [comment]
@jmfee-usgs Nice! Did it still not work in IE11 or Edge with the `babel-polyfill`? Edge is working on a native implementation, and both Edge and IE should work with polyfills; Angular's documentation links [here](https://www.webcomponents.org/polyfills)
